import {createHmac,randomBytes,scryptSync,timingSafeEqual} from "node:crypto";
import {SYSTEM_PROMPT_VERSION} from "./lib/core.mjs";import {supportedProviders} from "./lib/providers.mjs";
const failures=new Map(),audit=[];let settings={provider:process.env.AI_PROVIDER||"demo",model:process.env.AI_MODEL||"demo-reviewed-knowledge"};
const headers={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};const json=(status,body,extra={})=>({statusCode:status,headers:{...headers,...extra},body:JSON.stringify(body)});const cookies=e=>Object.fromEntries((e.headers?.cookie||"").split(/; */).filter(Boolean).map(x=>{const i=x.indexOf("=");return [x.slice(0,i),decodeURIComponent(x.slice(i+1))]}));
const sign=value=>createHmac("sha256",process.env.ADMIN_SESSION_SECRET||"").update(value).digest("hex");
function session(event){if(!process.env.ADMIN_SESSION_SECRET)return false;const raw=cookies(event).olm_admin;if(!raw)return false;const [payload,sig]=raw.split(".");if(!payload||!sig||!timingSafeEqual(Buffer.from(sign(payload)),Buffer.from(sig)))return false;try{return JSON.parse(Buffer.from(payload,"base64url")).expires>Date.now()}catch{return false}}
function issue(){const csrf=randomBytes(24).toString("hex"),payload=Buffer.from(JSON.stringify({role:"admin",expires:Date.now()+3600000})).toString("base64url");return {csrf,cookie:`olm_admin=${payload}.${sign(payload)}; Path=/; Max-Age=3600; HttpOnly; Secure; SameSite=Strict`}}
function verifyPassword(value){const [salt,expected]=[process.env.ADMIN_PASSWORD_SALT,process.env.ADMIN_PASSWORD_HASH];if(!salt||!expected)return false;const actual=scryptSync(String(value),salt,32);const target=Buffer.from(expected,"hex");return target.length===actual.length&&timingSafeEqual(actual,target)}
export async function handler(event){const action=event.queryStringParameters?.action||"settings",ip=event.headers?.["x-nf-client-connection-ip"]||"local";
 if(action==="login"&&event.httpMethod==="POST"){const state=failures.get(ip)||{count:0,until:0};if(state.until>Date.now())return json(429,{message:"로그인 시도가 잠시 제한되었습니다."});let body={};try{body=JSON.parse(event.body||"{}")}catch{}if(!verifyPassword(body.password)){state.count++;if(state.count>=5)state.until=Date.now()+900000;failures.set(ip,state);return json(401,{message:"인증에 실패했습니다."})}failures.delete(ip);const auth=issue();const response=json(200,{csrfToken:auth.csrf});response.multiValueHeaders={"set-cookie":[auth.cookie,`olm_csrf=${auth.csrf}; Path=/; Max-Age=3600; Secure; SameSite=Strict`]};return response}
 if(!session(event))return json(401,{message:"관리자 인증이 필요합니다."});
 if(["PUT","POST","DELETE"].includes(event.httpMethod)&&event.headers?.["x-csrf-token"]!==cookies(event).olm_csrf)return json(403,{message:"CSRF 검증에 실패했습니다."});
 const keyName=settings.provider==="anthropic"?"ANTHROPIC_API_KEY":settings.provider==="openai"?"OPENAI_API_KEY":null,key=keyName?process.env[keyName]:"";
 if(action==="settings"&&event.httpMethod==="GET")return json(200,{...settings,systemPromptVersion:SYSTEM_PROMPT_VERSION,keyConfigured:Boolean(key),keyLastFour:key?key.slice(-4):"",capabilities:["products","claims","evidence","advertising","metrics","audit"],auditCount:audit.length});
 if(action==="settings"&&event.httpMethod==="PUT"){let body;try{body=JSON.parse(event.body||"{}")}catch{return json(400,{message:"잘못된 요청입니다."})}if(!supportedProviders.includes(body.provider)||typeof body.model!=="string"||body.model.length>100)return json(400,{message:"설정값을 확인해 주세요."});settings={provider:body.provider,model:body.model};audit.push({at:new Date().toISOString(),actor:"admin",action:"ai.settings.updated",fields:["provider","model"]});return json(200,{saved:true})}
 if(action==="test"&&event.httpMethod==="POST")return json(key||settings.provider==="demo"?200:503,{connected:Boolean(key)||settings.provider==="demo",provider:settings.provider,message:key||settings.provider==="demo"?"연결 설정을 확인했습니다.":"공급자 API 키가 설정되지 않았습니다."});return json(405,{message:"Method not allowed"})}
