import test from "node:test";
import assert from "node:assert/strict";
import {readFile,access,readdir} from "node:fs/promises";
import {spawnSync} from "node:child_process";

const root=new URL("../",import.meta.url);
const pages=["index.html","about/index.html","brands/index.html","brands/ludwik/index.html","brands/biostar/index.html","business/index.html","partnership/index.html","contact/index.html"];
const logoPath="/docs/source-images/ChatGPT Image 2026년 8월 22일 오후 01_09_56.png";
const landingName="랜딩페이지이미지.png";
const biostarPngs=["biostar-bathroom-cleaner-700ml.png","biostar-dishwasher-tablets-50pcs.png","biostar-dishwashing-liquid-700ml.png","biostar-glass-and-mirror-cleaner-700ml.png","biostar-kitchen-cleaner-700ml.png","biostar-shower-cabin-cleaner-700ml.png","biostar-toilet-gel-750ml.png","biostar-universal-cleaner-800ml.png"];
const ludwikPngs=["ludwik-eko-dishwasher-tablets-40pcs.png","ludwik-eko-dishwasher-tablets-75pcs.png","ludwik-eko-dishwasher-tablets-120pcs.png","ludwik-eko-dishwasher-powder-1-2kg.png"];

const build=spawnSync(process.execPath,[new URL("../scripts/build.mjs",import.meta.url).pathname],{stdio:"inherit"});
assert.equal(build.status,0,"fixture build must succeed");

test("all routes exist",async()=>{for(const p of pages)await access(new URL(p,root))});
test("local absolute links resolve",async()=>{for(const p of pages){const html=await readFile(new URL(p,root),"utf8");for(const [,href] of html.matchAll(/href="(\/[^"]*)"/g)){const clean=href.split("#")[0].split("?")[0];if(!clean||clean==="/"){await access(new URL("index.html",root));continue}if(clean.includes("."))await access(new URL(clean.slice(1),root));else await access(new URL(`${clean.slice(1)}index.html`,root));}}});
test("images have dimensions and alt",async()=>{for(const p of pages){const html=await readFile(new URL(p,root),"utf8");for(const [tag] of html.matchAll(/<img\b[^>]*>/g)){assert.match(tag,/alt="[^"]*"/);assert.match(tag,/width="\d+"/);assert.match(tag,/height="\d+"/)}}});
test("rendered pages use the original image logo",async()=>{for(const p of pages){const html=await readFile(new URL(p,root),"utf8");assert.doesNotMatch(html,/OREUM|<span>OLM<\/span>|olm_logo\.png/);const expected=`<a class="logo" href="/"><img src="${logoPath}" width="320" height="120" alt="오름인터내셔널 OLM"></a>`;assert.match(html,new RegExp(`<header[^>]*>[\\s\\S]*?${expected.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}`));assert.match(html,new RegExp(`<footer[^>]*>[\\s\\S]*?${expected.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}`));}});
test("mobile header keeps the image logo visible",async()=>{const html=await readFile(new URL("index.html",root),"utf8");assert.match(html,/<div class="container header-inner"><a class="logo"[^>]*><img[^>]+alt="오름인터내셔널 OLM"[^>]*><\/a><button class="menu-button"/);const css=await readFile(new URL("assets/css/style.css",root),"utf8");assert.match(css,/@media\(max-width:800px\)\{\.logo\{/)});
test("hero uses the sharp original landing PNG and reduced motion",async()=>{const html=await readFile(new URL("index.html",root),"utf8");assert.match(html,/class="hero-background"/);const css=await readFile(new URL("assets/css/style.css",root),"utf8");assert.ok(css.includes(`/docs/source-images/${landingName}`));const backgroundRule=css.match(/\.hero-background\{([^}]*)\}/)?.[1]??"";assert.doesNotMatch(backgroundRule,/(?:backdrop-)?filter\s*:\s*blur\(/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);assert.match(css,/\.hero-background\{animation:none/)});
test("hero CTAs keep valid links and the retailer CTA has readable colors",async()=>{const html=await readFile(new URL("index.html",root),"utf8");assert.match(html,/<a class="btn btn-primary" href="\/brands\/">브랜드 살펴보기<\/a>/);assert.match(html,/<a class="btn btn-light" href="#retailers">공식 판매처 보기<\/a>/);const css=await readFile(new URL("assets/css/style.css",root),"utf8");const retailerRule=css.match(/\.hero \.btn-light\{([^}]*)\}/)?.[1]??"";assert.match(retailerRule,/background:#fff/);assert.match(retailerRule,/color:#0b2239/);assert.match(css,/\.hero \.btn-light:focus-visible\{outline:3px solid #ffc857/)});
test("home scroll cue is accessible, one-time, and targets the next section",async()=>{const html=await readFile(new URL("index.html",root),"utf8");assert.match(html,/<button class="hero-scroll-cue" type="button" aria-label="다음 콘텐츠로 이동" aria-controls="home-introduction">/);assert.match(html,/<svg[^>]+aria-hidden="true"/);assert.match(html,/<section class="trust-strip" id="home-introduction" tabindex="-1"/);const js=await readFile(new URL("assets/js/main.js",root),"utf8");assert.match(js,/window\.scrollY >= 64/);assert.match(js,/scrollCue\.hidden = true/);assert.match(js,/reducedMotion\.matches \? "auto" : "smooth"/);const css=await readFile(new URL("assets/css/style.css",root),"utf8");assert.match(css,/animation:hero-drift 12s ease-in-out infinite alternate/);assert.match(css,/animation:scroll-cue 1\.8s ease-in-out infinite/)});
test("build copies only the approved source PNGs",async()=>{const names=await readdir(new URL("dist/docs/source-images/",root));assert.deepEqual(names.sort(),[
  logoPath.split("/").at(-1), landingName, "Ludwik-logo.png",
  "ChatGPT Image 2026년 8월 22일 오후 01_55_15 (5).png",
  "ChatGPT Image 2026년 8월 22일 오후 01_55_15 (6).png",
  "ChatGPT Image 2026년 8월 22일 오후 02_10_04.png",
  "ChatGPT Image 2026년 8월 22일 오후 02_15_58.png", ...biostarPngs, ...ludwikPngs
].sort())});
test("brand detail pages render approved product assets",async()=>{const ludwik=await readFile(new URL("brands/ludwik/index.html",root),"utf8");const biostar=await readFile(new URL("brands/biostar/index.html",root),"utf8");assert.match(ludwik,/src="\/docs\/source-images\/Ludwik-logo\.png"/);assert.equal((ludwik.match(/data-product-id=/g)||[]).length,3);for(const name of ludwikPngs)assert.match(ludwik,new RegExp(`src="/docs/source-images/${name.replaceAll(".","\\.")}"`));assert.equal((biostar.match(/data-product-id=/g)||[]).length,8);for(const name of biostarPngs)assert.match(biostar,new RegExp(`src="/docs/source-images/${name.replaceAll(".","\\.")}"`));assert.doesNotMatch(biostar,/brand-wordmark|<img[^>]+alt="BIOstar"/);for(const html of [ludwik,biostar])assert.doesNotMatch(html,/src="[^"]+\.(?:tif|pdf)"/i)});
test("Ludwik catalogue stays data-driven and groups tablet variants",async()=>{const source=await readFile(new URL("src/content/ko/ludwik.js",root),"utf8");assert.equal((source.match(/familyId: "ludwik-eko-dishwasher-tablets"/g)||[]).length,3);assert.equal((source.match(/purchaseUrl: null/g)||[]).length,4);assert.match(source,/officialPurchaseUrl: null/);assert.doesNotMatch(source,/futureImage|imageReady|product-placeholder|\.tiff?\b/i)});
test("BIOstar catalogue and unset claims stay data-driven",async()=>{const source=await readFile(new URL("src/content/ko/biostar.js",root),"utf8");assert.equal((source.match(/certifications: \[\]/g)||[]).length,8);assert.equal((source.match(/purchaseUrl: null/g)||[]).length,8);assert.match(source,/TODO: 공식 BIOstar 로고 업로드 후 교체/);assert.match(source,/logo: \{ path: null/);assert.match(source,/officialPurchaseUrl: null/);assert.doesNotMatch(source,/futureImage|imageReady|\.tiff?\b/i)});
test("only Korean locale SEO is published",async()=>{for(const p of pages){const html=await readFile(new URL(p,root),"utf8");assert.match(html,/<html lang="ko">/);assert.match(html,/property="og:locale" content="ko_KR"/);assert.doesNotMatch(html,/hreflang=|lang="en"|https:\/\/example\.com\/en\//)}await assert.rejects(access(new URL("en/index.html",root)))});
test("sitemap contains no unpublished English routes",async()=>{const sitemap=await readFile(new URL("sitemap.xml",root),"utf8");assert.doesNotMatch(sitemap,/\/en\//)});
