/** Korean page content. Keep the exported shape aligned with a future reviewed locale module. */
export const homeContentKo = ({ imageTag }) => (
`<section class="hero"><div class="hero-background" aria-hidden="true"></div><div class="hero-overlay" aria-hidden="true"></div><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Official partner in Korea</span><h1 class="display">유럽 프리미엄 생활용품 브랜드의<br>한국 공식 파트너</h1><p>오름인터내셔널이 Ludwik와 BIOstar를 대한민국에 공식적으로 소개합니다.</p><div class="btn-row"><a class="btn btn-primary" href="/brands/">브랜드 살펴보기</a><a class="btn btn-light" href="#retailers">공식 판매처 보기</a></div></div></div><button class="hero-scroll-cue" type="button" aria-label="다음 콘텐츠로 이동" aria-controls="home-introduction"><span>SCROLL</span><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg></button></section>
<section class="trust-strip" id="home-introduction" tabindex="-1" aria-label="오름인터내셔널의 약속"><div class="container trust-inner"><strong>브랜드의 가치가 한국의 일상에 닿도록</strong><span>Official partnership · Local market expertise · Sustainable growth</span></div></section>
<section class="section ludwik"><div class="container split"><div><span class="eyebrow">Ludwik</span><div class="stat">1964</div><h2 class="title">생활의 깨끗함을 이어온 폴란드 홈케어</h2><p class="lead">1964년부터 이어온 폴란드의 생활 세정 브랜드, Ludwik. 주방에서 세탁과 홈케어까지, 오랜 경험을 바탕으로 일상의 깨끗함을 만들어갑니다.</p><div class="keyword-list"><span>Poland</span><span>Kitchen</span><span>Laundry</span></div><a class="link-arrow" href="/brands/ludwik/">Ludwik 자세히 보기 →</a></div><div class="visual">${imageTag("ludwikHero")}<span class="visual-label">Since 1964 · Poland</span></div></div></section>
<section class="section biostar"><div class="container split"><div class="visual">${imageTag("biostarHero")}<span class="visual-label">Nature × Cleaning technology</span></div><div><span class="eyebrow">BIOstar</span><h2 class="title">자연에서 찾은 성분에<br>클리닝 기술을 더하다</h2><p class="lead">천연 유래 성분과 식물 추출물에서 시작한 BIOstar. 알로에와 유산균을 활용한 새로운 클리닝 아이디어로 집 안의 다양한 공간을 깨끗하게 관리합니다.</p><div class="keyword-list"><span>천연 알로에 추출물</span><span>천연 라벤더 추출물</span><span>유산균</span></div><a class="link-arrow" href="/brands/biostar/">BIOstar 자세히 보기 →</a></div></div></section>
<section class="section"><div class="container"><span class="eyebrow">What we do</span><h2 class="title">좋은 브랜드를 발견하고<br>한국 시장의 성장을 설계합니다</h2><div class="cap-grid"><article class="cap-item"><span class="num">01</span><h3>브랜드 소싱</h3><p>시장과 고객의 생활을 이해해 성장 가능성이 있는 해외 브랜드를 발굴합니다.</p></article><article class="cap-item"><span class="num">02</span><h3>브랜드 빌딩</h3><p>브랜드 본연의 가치를 존중하며 한국 소비자에게 맞는 언어로 전달합니다.</p></article><article class="cap-item"><span class="num">03</span><h3>채널 운영</h3><p>온라인 유통 경험을 토대로 브랜드와 고객이 만나는 접점을 운영합니다.</p></article></div></div></section>
<section class="section-sm" id="retailers"><div class="container"><span class="eyebrow">Official retailers</span><h2 class="title">공식 판매채널</h2><p class="lead">신뢰할 수 있는 공식 판매처를 준비하고 있습니다. 판매처가 확정되는 대로 이곳에서 안내합니다.</p><div class="notice">공식 판매처 링크 업데이트 예정</div></div></section>
<section class="section dark"><div class="container b2b"><div><span class="eyebrow">Partnership</span><h2 class="title">한국 시장의 다음 성장을<br>함께 만들 브랜드를 기다립니다</h2><p class="lead">브랜드 발굴부터 현지화, 유통 운영과 장기적인 브랜드 빌딩까지 함께합니다.</p></div><a class="btn btn-light" href="/partnership/">파트너십 알아보기</a></div></section>`
);
