/** Korean home content. Product guide links are intentionally navigational until an API is approved. */
export const homeContentKo = () => (
`<section class="hero"><div class="hero-background" aria-hidden="true"></div><div class="hero-overlay" aria-hidden="true"></div><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Official partner in Korea</span><h1 class="display">유럽 프리미엄 생활용품 브랜드<br>한국 공식 파트너</h1><p>오름인터내셔널이 Ludwik와 BIOstar를 대한민국에 공식적으로 소개합니다.</p><div class="btn-row"><a class="btn btn-primary" href="/brands/">브랜드 살펴보기</a><a class="btn btn-light" href="https://smartstore.naver.com/olmmall" target="_blank" rel="noopener noreferrer">공식 판매처 보기</a></div></div></div><button class="hero-scroll-cue" type="button" aria-label="다음 콘텐츠로 이동" aria-controls="home-introduction"><span>SCROLL</span><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg></button></section>
<section class="trust-strip" id="home-introduction" tabindex="-1" aria-label="오름인터내셔널의 약속"><div class="container trust-inner"><strong>브랜드의 가치가 한국의 일상에 닿도록</strong><span>Official partnership · Local market expertise · Sustainable growth</span></div></section>
<section class="section brand-showcase reveal" aria-labelledby="brands-title"><div class="container"><header class="section-heading"><span class="eyebrow">OUR BRANDS</span><h2 class="title" id="brands-title">유럽 생활용품 브랜드를 한국 일상으로</h2><p class="lead">오름인터내셔널은 Ludwik와 BIOstar의 브랜드 가치와 제품 정보를 국내 소비자에게 정확하게 전달합니다.</p></header><div class="brand-editorial">
<a class="brand-panel brand-panel-ludwik" href="/brands/ludwik/"><div class="brand-copy"><span class="brand-label">LUDWIK · POLAND · SINCE 1964</span><h3>1964년부터 이어온<br>폴란드 홈케어</h3><p>폴란드의 주방 세정에서 시작해 세탁과 생활공간 관리로 제품군을 확장해 온 생활 세정 브랜드입니다.</p><ul aria-label="Ludwik 제품군"><li>주방</li><li>식기세척기</li><li>세탁</li><li>홈케어</li></ul><span class="panel-cta">Ludwik 살펴보기 <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-ludwik"><img src="/docs/source-images/ludwik-eko-dishwasher-tablets-120pcs.png" width="2724" height="3587" alt="Ludwik EKO 식기세척기용 태블릿 120개입 패키지" loading="lazy" decoding="async"><img src="/docs/source-images/ludwik-eko-dishwasher-powder-1-2kg.png" width="2362" height="3154" alt="Ludwik EKO 식기세척기용 분말 세제 1.2kg 패키지" loading="lazy" decoding="async"></div></a>
<!-- TODO: 공식 BIOstar 로고가 제공되면 brand-label 위치에 이미지 자산을 연결합니다. -->
<a class="brand-panel brand-panel-biostar" href="/brands/biostar/"><div class="brand-copy"><span class="brand-label">BIOSTAR · POLAND</span><h3>공간과 용도에 맞춘<br>생활 세정</h3><p>폴란드 INCO 그룹이 선보이는 홈케어 브랜드로, 주방과 욕실 등 생활공간에 맞춘 세정 제품을 소개합니다.</p><ul aria-label="BIOstar 제품군"><li>주방 관리</li><li>욕실 관리</li><li>다목적 관리</li><li>식기세척기 관리</li></ul><span class="panel-cta">BIOstar 살펴보기 <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-biostar"><img src="/docs/source-images/biostar-kitchen-cleaner-700ml.png" width="854" height="2270" alt="BIOstar 주방 세정 폼 700ml 스프레이 용기" loading="lazy" decoding="async"><img src="/docs/source-images/biostar-bathroom-cleaner-700ml.png" width="854" height="2270" alt="BIOstar 욕실 세정 폼 700ml 스프레이 용기" loading="lazy" decoding="async"></div></a>
</div></div></section>
<section class="section product-guide reveal" aria-labelledby="guide-title"><div class="container guide-layout"><div><span class="eyebrow">PRODUCT GUIDE</span><h2 class="title" id="guide-title">어떤 제품이 필요한지<br>쉽게 찾아보세요</h2></div><div class="guide-copy"><p>공간과 사용 목적에 따라 Ludwik와 BIOstar 제품 정보를 확인할 수 있습니다. 제품별 용도와 사용 방법을 안내하는 AI 제품 가이드를 준비하고 있습니다.</p><small>AI 제품 가이드 준비 중</small><nav aria-label="제품 안내 링크"><a href="/brands/ludwik/">Ludwik 제품 보기 <span aria-hidden="true">→</span></a><a href="/brands/biostar/">BIOstar 제품 보기 <span aria-hidden="true">→</span></a><a href="/ai-clean-care/">제품 문의하기 <span aria-hidden="true">→</span></a></nav><!-- FUTURE API: 승인된 productGuide 데이터 API가 확정되면 이 정적 nav를 독립 ProductGuide 컴포넌트로 교체합니다. --></div></div></section>
<section class="section market-partner reveal" aria-labelledby="market-title"><div class="container"><header class="section-heading"><span class="eyebrow">KOREA MARKET PARTNER</span><h2 class="title" id="market-title">브랜드의 가능성을<br>한국 시장의 성장으로 연결합니다</h2><p class="lead">오름인터내셔널은 해외 생활용품 브랜드가 한국 소비자와 만날 수 있도록 시장 검토부터 브랜드 운영과 유통채널 관리까지 함께합니다.</p></header><ol class="market-flow"><li class="reveal-step"><span>01</span><div><h3>브랜드 발굴 및 시장 검토</h3><p>브랜드와 제품의 특성을 확인하고 국내 시장 및 소비자와의 적합성을 검토합니다.</p></div></li><li class="reveal-step"><span>02</span><div><h3>현지화 및 브랜드 구축</h3><p>국내 소비자에게 브랜드 가치가 정확하게 전달되도록 콘텐츠와 커뮤니케이션을 설계합니다.</p></div></li><li class="reveal-step"><span>03</span><div><h3>유통채널 운영 및 성장</h3><p>국내 온라인 유통채널을 운영하고 시장 반응을 바탕으로 브랜드의 지속적인 성장을 지원합니다.</p></div></li></ol><div class="partner-callout"><div><h3>한국 시장을 함께 만들어갈 브랜드를 찾습니다</h3><p>한국 시장 진출과 브랜드 운영을 함께할 해외 생활용품 브랜드의 제안을 기다립니다.</p></div><a class="link-arrow" href="/partnership/">파트너십 알아보기 →</a></div></div></section>
<section class="section-sm retailer-status reveal" id="retailers" aria-labelledby="retailers-title"><div class="container retailer-layout"><div><span class="eyebrow">OFFICIAL RETAILERS</span><h2 id="retailers-title">공식 판매채널</h2><p>확인된 공식 판매채널을 순차적으로 안내할 예정입니다.</p><strong>판매채널 업데이트 예정</strong></div><nav aria-label="판매채널 관련 링크"><a href="/ai-clean-care/">제품 문의하기 →</a><a href="/brands/">브랜드 살펴보기 →</a></nav></div></section>`
);
