/** Korean page content. Keep the exported shape aligned with a future reviewed locale module. */
const retailerLogos = [
  { name: "쿠팡", image: "/docs/source-images/retailers/retailer-coupang.png", alt: "쿠팡", width: 2106, height: 747 },
  { name: "네이버 스마트스토어", image: "/docs/source-images/retailers/retailer-naver-smartstore.png", alt: "네이버 스마트스토어", width: 2169, height: 725, theme: "charcoal" },
  { name: "옥션", image: "/docs/source-images/retailers/retailer-auction.png", alt: "옥션", width: 2172, height: 724 },
  { name: "11번가", image: "/docs/source-images/retailers/retailer-11st.png", alt: "11번가", width: 1774, height: 887 },
  { name: "G마켓", image: "/docs/source-images/retailers/retailer-gmarket.png", alt: "G마켓", width: 2106, height: 747 },
  { name: "SSG.COM", image: "/docs/source-images/retailers/retailer-ssg.png", alt: "SSG.COM", width: 2069, height: 760 },
  { name: "이마트몰", image: "/docs/source-images/retailers/retailer-emart-mall.png", alt: "이마트몰", width: 2172, height: 724, theme: "yellow" },
  { name: "코스트코", image: "/docs/source-images/retailers/retailer-costco.png", alt: "코스트코", width: 2021, height: 778 }
];

const renderRetailerGroup = (duplicate = false) => `<div class="retailer-marquee-group"${duplicate ? ' aria-hidden="true"' : ""}>${retailerLogos.map(({ name, image, alt, width, height, theme }) => `<div class="retailer-logo${theme ? ` retailer-logo--${theme}` : ""}" title="${name}"><img src="${image}" width="${width}" height="${height}" alt="${duplicate ? "" : alt}"></div>`).join("")}</div>`;

const retailerLandscape = `<section class="retailer-landscape" aria-labelledby="retailer-landscape-title"><div class="container retailer-landscape-heading"><span class="eyebrow">Retail landscape</span><h2 class="title" id="retailer-landscape-title">한국의 주요 온라인 유통채널</h2><p class="lead">브랜드의 특성과 국내 판매 전략에 맞는 유통채널을 검토하고, 한국 소비자와 효과적으로 연결될 수 있도록 지원합니다.</p></div><div class="retailer-marquee" tabindex="0" aria-label="국내 주요 온라인 유통채널 로고"><div class="retailer-marquee-track">${renderRetailerGroup()}${renderRetailerGroup(true)}</div></div></section>`;

export const partnershipContentKo = ({ pageHero }) => (
`${pageHero("Partnership","Your trusted partner<br>for the Korean market","We help international homecare brands enter, connect, and grow in Korea with a long-term perspective.")}<section class="section"><div class="container split"><div><span class="eyebrow">Local expertise</span><h2 class="title">브랜드의 기준을 지키며<br>한국 시장과 연결합니다</h2></div><div><p class="lead">오름인터내셔널은 단순한 유통을 넘어 브랜드의 목소리와 한국 소비자의 기대 사이를 연결합니다. 시장 이해, 현지화, 채널 운영을 하나의 팀처럼 함께합니다.</p></div></div></section>${retailerLandscape}<section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">Our support</span><h2 class="title">지원 범위</h2><div class="feature-row"><article><h3>Market entry</h3><p>시장 맥락과 고객 접점을 고려한 진입 방향을 함께 설계합니다.</p></article><article><h3>Brand building</h3><p>브랜드 아이덴티티를 존중하는 현지 콘텐츠와 커뮤니케이션을 구축합니다.</p></article><article><h3>Channel operation</h3><p>공식 판매채널을 운영하고 지속적인 성장을 위한 기반을 관리합니다.</p></article></div></div></section><section class="section"><div class="container"><span class="eyebrow">How we collaborate</span><h2 class="title">협업 절차</h2><div class="timeline"><article><time>STEP 01</time><h3>Introduction</h3><p>브랜드와 제품, 한국 시장에서의 목표를 공유합니다.</p></article><article><time>STEP 02</time><h3>Market &amp; fit review</h3><p>제품군과 시장 적합성, 협업 범위를 함께 검토합니다.</p></article><article><time>STEP 03</time><h3>Launch plan</h3><p>현지화, 채널, 마케팅 실행 계획을 구체화합니다.</p></article><article><time>STEP 04</time><h3>Grow together</h3><p>론칭 이후 성과를 살피며 장기적인 성장을 만듭니다.</p></article></div></div></section><section class="section dark partnership-cta"><div class="container b2b"><div><h2 class="title">Let’s build your brand’s<br>next chapter in Korea.</h2><p class="lead">영문 제안 자료와 상세 협업 문의는 연락처를 통해 요청해 주세요.</p></div><a class="btn btn-light" href="/contact/?type=partnership">파트너십 문의</a></div></section>`
);
