import { mkdir, readFile, writeFile } from "node:fs/promises";
import { renderLanguageSwitcher } from "../src/components/language-switcher.js";
import { renderMetadata } from "../src/seo/metadata.js";

const root=new URL("../",import.meta.url), site="https://olm.kr";
const master=JSON.parse(await readFile(new URL("assets/data/product-master.json",root),"utf8"));
const logoPath="/docs/source-images/ChatGPT Image 2026년 8월 22일 오후 01_09_56.png";
const nav=[['about','About'],['brands','Brands'],['business','Business'],['partnership','Partnerships'],['ai-clean-care','AI Clean Care'],['contact','Contact']];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const koPath=path=>path.replace(/^\/en/,"")||"/";
const header=(current,path)=>`<a class="skip-link" href="#main">Skip to content</a><header class="header"><div class="container header-inner"><a class="logo"${current==="home"?' data-home-header-logo':''} href="/en/"><img src="${logoPath}" width="320" height="120" alt="OLM International"></a><button class="menu-button" id="menu-open" aria-controls="primary-nav" aria-expanded="false"><span></span><span></span><span></span><span class="sr-only">Open menu</span></button><nav class="nav" id="primary-nav" aria-label="Primary navigation"><button class="menu-close" id="menu-close" aria-label="Close menu">✕</button>${nav.map(([id,label])=>`<a href="/en/${id}/"${current===id?' aria-current="page"':''}>${label}</a>`).join("")}${renderLanguageSwitcher({currentLocale:"en",koreanPath:koPath(path),englishPath:path})}</nav></div></header>`;
const footer=`<footer class="footer"><div class="container"><div class="footer-top"><a class="logo" href="/en/"><img src="${logoPath}" width="320" height="120" alt="OLM International"></a><div class="footer-info"><span><b>Company</b> OLM International Corp.</span><span><b>Email</b> <a href="mailto:khs@olm.kr">khs@olm.kr</a></span><span><b>Phone</b> <a href="tel:07087799669">070-8779-9669</a></span><span><b>Address</b> 5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea</span></div></div><div class="footer-bottom">© 2026 OLM International Corp. All rights reserved. &nbsp; <a href="/en/contact/">Contact</a><a class="footer-admin" href="/admin/ai-clean-care/">Admin</a></div></div></footer>`;
const alternates=path=>({ko:`${site}${koPath(path)}`,en:`${site}${path}`});
const layout=({path,id,title,description,body,jsonLd})=>{const metadata={lang:"en",title,description,canonical:`${site}${path}`,alternates:alternates(path),openGraph:{title,description,locale:"en_US",url:`${site}${path}`,image:`${site}/assets/common/og/olm-og-olm-international-corp.svg`}};return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${renderMetadata(metadata)}<link rel="icon" href="/assets/common/icons/favicon.png" type="image/png"><link rel="stylesheet" href="/assets/css/style.css">${jsonLd?`<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<","\\u003c")}</script>`:""}</head><body>${header(id,path)}<main id="main">${body}</main>${footer}<script src="/assets/data/site-data.js"></script><script src="/assets/js/main.js"></script></body></html>`};
const hero=(label,title,lead)=>`<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/en/">Home</a> / ${label}</div><span class="eyebrow">${label}</span><h1 class="display">${title}</h1><p class="lead">${lead}</p></div></section>`;
const pages={
 home:{title:"OLM International | Connecting European Homecare Brands with Korea",description:"Meet OLM International and the Ludwik and BIOstar homecare brands in Korea.",body:`<section class="hero"><div class="hero-background" aria-hidden="true"></div><div class="hero-overlay" aria-hidden="true"></div><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Official partner in Korea</span><h1 class="display">European premium homecare brands,<br>Korea’s official partner</h1><p>OLM International officially introduces Ludwik and BIOstar to Korea.</p><div class="btn-row"><a class="btn btn-primary" href="/en/brands/">Explore our brands</a><a class="btn btn-light" href="https://smartstore.naver.com/olmmall" target="_blank" rel="noopener noreferrer">Visit the official store</a></div></div></div><button class="hero-scroll-cue" type="button" aria-label="Go to the next section" aria-controls="home-introduction"><span>SCROLL</span><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg></button></section>
<section class="trust-strip" id="home-introduction" tabindex="-1" aria-label="OLM International commitment"><div class="container trust-inner"><strong>Bringing brand value into everyday life in Korea</strong><span>Official partnership · Local market expertise · Sustainable growth</span></div></section>
<section class="section brand-showcase reveal" aria-labelledby="brands-title"><div class="container"><header class="section-heading"><span class="eyebrow">OUR BRANDS</span><h2 class="title" id="brands-title">European homecare brands for everyday life in Korea</h2><p class="lead">OLM International accurately communicates the brand values and product information of Ludwik and BIOstar to Korean consumers.</p></header><div class="brand-editorial">
<a class="brand-panel brand-panel-ludwik" href="/en/brands/ludwik/"><div class="brand-copy"><span class="brand-label">LUDWIK · POLAND · SINCE 1964</span><h3>Polish homecare<br>since 1964</h3><p>A household cleaning brand that began in the Polish kitchen and expanded into laundry and homecare.</p><ul aria-label="Ludwik product categories"><li>Kitchen</li><li>Dishwasher</li><li>Laundry</li><li>Homecare</li></ul><span class="panel-cta">Explore Ludwik <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-ludwik"><img src="/docs/source-images/ludwik-eko-dishwasher-tablets-120pcs.png" width="2724" height="3587" alt="Ludwik EKO dishwasher tablets 120-count package" loading="lazy" decoding="async"><img src="/docs/source-images/ludwik-eko-dishwasher-powder-1-2kg.png" width="2362" height="3154" alt="Ludwik EKO dishwasher powder 1.2 kg package" loading="lazy" decoding="async"></div></a>
<a class="brand-panel brand-panel-biostar" href="/en/brands/biostar/"><div class="brand-copy"><span class="brand-label">BIOSTAR · POLAND</span><h3>Everyday cleaning<br>by space and purpose</h3><p>A homecare brand from Poland’s INCO Group, offering cleaning products for kitchens, bathrooms and everyday spaces.</p><ul aria-label="BIOstar product categories"><li>Kitchen care</li><li>Bathroom care</li><li>Multi-purpose care</li><li>Dishwasher care</li></ul><span class="panel-cta">Explore BIOstar <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-biostar"><img src="/docs/source-images/biostar-kitchen-cleaner-700ml.png" width="854" height="2270" alt="BIOstar kitchen cleaning foam 700 ml bottle" loading="lazy" decoding="async"><img src="/docs/source-images/biostar-bathroom-cleaner-700ml.png" width="854" height="2270" alt="BIOstar bathroom cleaning foam 700 ml bottle" loading="lazy" decoding="async"></div></a>
</div></div></section>
<section class="section product-guide reveal" aria-labelledby="guide-title"><div class="container guide-layout"><div><span class="eyebrow">PRODUCT GUIDE</span><h2 class="title" id="guide-title">Find the product<br>you need with ease</h2></div><div class="guide-copy"><p>Explore Ludwik and BIOstar products by space and purpose. Our AI product guide provides information about product uses and directions.</p><small>AI product guide available</small><nav aria-label="Product guide links"><a href="/en/brands/ludwik/">View Ludwik products <span aria-hidden="true">→</span></a><a href="/en/brands/biostar/">View BIOstar products <span aria-hidden="true">→</span></a><a href="/en/ai-clean-care/">Ask about a product <span aria-hidden="true">→</span></a></nav></div></div></section>
<section class="section market-partner reveal" aria-labelledby="market-title"><div class="container"><header class="section-heading"><span class="eyebrow">KOREA MARKET PARTNER</span><h2 class="title" id="market-title">Connecting brand potential<br>with growth in Korea</h2><p class="lead">OLM International supports international homecare brands from market review through brand operations and distribution channel management.</p></header><ol class="market-flow"><li class="reveal-step"><span>01</span><div><h3>Brand sourcing and market review</h3><p>We evaluate each brand and product for its fit with the Korean market and consumers.</p></div></li><li class="reveal-step"><span>02</span><div><h3>Localization and brand building</h3><p>We design content and communication that accurately convey brand value to Korean consumers.</p></div></li><li class="reveal-step"><span>03</span><div><h3>Channel operation and growth</h3><p>We operate local online channels and support sustainable growth based on market response.</p></div></li></ol><div class="partner-callout"><div><h3>We are looking for brands ready to grow in Korea</h3><p>We welcome proposals from international homecare brands seeking market entry and long-term operations in Korea.</p></div><a class="link-arrow" href="/en/partnership/">Explore partnerships →</a></div></div></section>
<section class="section-sm retailer-status reveal" id="retailers" aria-labelledby="retailers-title"><div class="container retailer-layout"><div><span class="eyebrow">OFFICIAL RETAILERS</span><h2 id="retailers-title">Official sales channels</h2><p>Verified official sales channels will be listed here as they become available.</p><strong>Sales channel updates coming soon</strong></div><nav aria-label="Sales channel links"><a href="/en/ai-clean-care/">Ask about a product →</a><a href="/en/brands/">Explore our brands →</a></nav></div></section>`},
 about:{title:"About | OLM International",description:"Learn how OLM International connects international homecare brands with the Korean market.",body:hero("About","We understand brands.<br>We build lasting growth.","OLM International connects brands and consumers with a long-term view of the Korean market.")+`<section class="section"><div class="container split"><div><span class="eyebrow">WHO WE ARE</span><h2 class="title">A partner that connects brand value with the Korean market</h2></div><div><p class="lead">We go beyond distribution. We review the market, localize communication and operate sales channels so that each brand can meet Korean consumers in the right way.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">OUR APPROACH</span><div class="feature-row"><article><h3>Understand</h3><p>We begin with the brand, product and market context.</p></article><article><h3>Connect</h3><p>We shape local content and consumer touchpoints while preserving brand identity.</p></article><article><h3>Grow</h3><p>We manage channels and support sustainable, long-term market development.</p></article></div></div></section>`},
 brands:{title:"Brands | OLM International",description:"Explore Ludwik and BIOstar, the homecare brands introduced in Korea by OLM International.",body:hero("Brands","Brands for everyday care","Discover the homecare brands and verified product information introduced by OLM International.")+`<section class="section brand-showcase"><div class="container"><div class="brand-editorial"><a class="brand-panel brand-panel-ludwik" href="/en/brands/ludwik/"><div class="brand-copy"><span class="brand-label">LUDWIK · POLAND</span><h3>Homecare experience<br>since 1964</h3><p>A Polish cleaning brand whose experience began in the kitchen and expanded across everyday homecare.</p><span class="panel-cta">Explore Ludwik →</span></div></a><a class="brand-panel brand-panel-biostar" href="/en/brands/biostar/"><div class="brand-copy"><span class="brand-label">BIOSTAR · POLAND</span><h3>Cleaning solutions<br>for everyday spaces</h3><p>A GRUPA INCO homecare brand with products for kitchens, bathrooms and other household spaces.</p><span class="panel-cta">Explore BIOstar →</span></div></a></div></div></section>`},
 business:{title:"Business | OLM International",description:"OLM International supports brand sourcing, localization, brand building and online distribution in Korea.",body:hero("Business","From brand sourcing<br>to market growth","We connect international homecare brands with the Korean market through an integrated operating approach.")+`<section class="section"><div class="container"><div class="cap-grid"><article class="cap-item"><span class="num">01</span><h3>Brand sourcing</h3><p>We review products, positioning and fit with the Korean market.</p></article><article class="cap-item"><span class="num">02</span><h3>Localization &amp; brand building</h3><p>We develop market communication that respects the brand’s identity.</p></article><article class="cap-item"><span class="num">03</span><h3>Channel operation</h3><p>We operate online sales channels and manage consumer touchpoints.</p></article></div></div></section>`},
 partnership:{title:"Korea Market Partnerships | OLM International",description:"Partner with OLM International to review and develop opportunities for homecare brands in Korea.",body:hero("Partnership","Your trusted partner<br>for the Korean market","We help international homecare brands enter, connect and grow in Korea with a long-term perspective.")+`<section class="section"><div class="container split"><div><span class="eyebrow">LOCAL EXPERTISE</span><h2 class="title">Protecting brand standards while connecting with Korea</h2></div><div><p class="lead">We work as one team across market understanding, localization and channel operation.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">OUR SUPPORT</span><div class="feature-row"><article><h3>Market entry</h3><p>We shape an entry direction around the market and customer journey.</p></article><article><h3>Brand building</h3><p>We build local content and communication that respect brand identity.</p></article><article><h3>Channel operation</h3><p>We operate official sales channels and manage the foundation for continued growth.</p></article></div></div></section><section class="section dark partnership-cta"><div class="container b2b"><div><h2 class="title">Let’s build your brand’s<br>next chapter in Korea.</h2></div><a class="btn btn-light" href="/en/contact/?type=partnership">Partnership inquiry</a></div></section>`},
 contact:{title:"Contact | OLM International",description:"Contact OLM International about products, distribution and international brand partnerships.",body:hero("Contact","Let’s start a conversation","Select the purpose of your inquiry and share the details with our team.")+`<section class="section"><div class="container contact-grid"><aside><span class="eyebrow">CONTACT INFORMATION</span><h2 class="title">Get in touch</h2><ul class="contact-list"><li><b>Company</b><br>OLM International Corp.</li><li><b>Email</b><br><a href="mailto:khs@olm.kr">khs@olm.kr</a></li><li><b>Phone</b><br><a href="tel:07087799669">070-8779-9669</a></li><li><b>Address</b><br>5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea</li></ul></aside><div><form id="contact-form"><div class="form-grid"><div class="field"><label for="type">Inquiry type</label><select id="type" name="type" required><option value="">Please select</option><option>Consumer inquiry</option><option>Distribution inquiry</option><option>International brand partnership</option></select></div><div class="field"><label for="name">Name / Company</label><input id="name" name="name" autocomplete="name" maxlength="120" required></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" maxlength="254" required></div><div class="field"><label for="phone">Phone <span class="sr-only">Optional</span></label><input id="phone" name="phone" autocomplete="tel" maxlength="60"></div><div class="field full"><label for="message">Message</label><textarea id="message" name="message" maxlength="5000" required></textarea></div><div class="field full"><label><input type="checkbox" required> I agree to the collection of personal information required to respond to this inquiry.</label></div></div><button class="btn btn-primary" type="submit">Review inquiry</button><p class="form-status" id="form-status" tabindex="-1" role="status">Please complete the inquiry form.</p></form></div></div></section>`},
 'ai-clean-care':{title:"AI Clean Care | OLM International",description:"Ask about product selection, ingredients, directions and advertising claims using verified product information.",body:`<section class="ai-hero"><div class="container ai-hero-grid"><div><nav class="breadcrumb"><a href="/en/">Home</a> / AI Clean Care</nav><span class="eyebrow">AI CLEAN CARE</span><h1 class="display">Questions about detergents?<br>Ask AI Clean Care.</h1><p class="lead">Get guidance based on verified product information and cleaning knowledge.</p></div></div></section><section class="section ai-workspace"><div class="container ai-layout"><div class="ai-main"><form id="ai-care-form" class="ai-question-card"><div class="ai-card-index">01 · ASK</div><label for="ai-question">What would you like to check?</label><textarea id="ai-question" name="question" maxlength="1200" rows="5" required placeholder="Ask about a product, ingredient, area of use or advertising statement."></textarea><div class="ai-form-meta"><span>Do not enter personal or sensitive information.</span><span id="ai-char-count">0 / 1,200</span></div><button class="btn btn-primary" type="submit">Ask AI <span aria-hidden="true">→</span></button></form><section class="ai-result" id="ai-result" hidden tabindex="-1"><div class="ai-section-heading"><span>02</span><h2>AI response</h2></div><div id="ai-status" class="ai-status" role="status" aria-live="polite"></div><div id="ai-answer"></div><button class="btn ai-deep-button" id="ai-deep-button" type="button" hidden>Explore in more detail →</button></section><section class="ai-deep-result" id="ai-deep-result" hidden tabindex="-1"><div class="ai-section-heading"><span>03</span><h2>Detailed response</h2></div><div id="ai-deep-status" class="ai-status" role="status"></div><div id="ai-deep-answer"></div></section></div></div></section>`}
};
const productEnglish={
 "dishwashing-liquid":{name:"BIOstar Dishwashing Liquid",purpose:"Hand-washing dishes and cookware",description:"A hand dishwashing liquid made with a formula containing 97% ingredients of natural origin according to official manufacturer information. It contains natural aloe extract and glycerin and cleans grease and food residue from dishes and cookware.",usage:"Apply an appropriate amount to a sponge or dish, wash, and rinse thoroughly under running water. Follow the recommended amount on the product label.",cautions:"Use only as directed and review the cautions on the product label before use. Follow the recommended amount to reduce environmental impact.",features:["97% ingredients of natural origin according to official manufacturer information","Contains natural aloe extract and glycerin","Cleans grease and food residue from dishes and cookware","Biodegradable ingredient-based formula, as described by the manufacturer","EU Ecolabel certification (PL/019/009)","Recyclable container, as described by the manufacturer"]},
 "kitchen-cleaner":{name:"BIOstar Kitchen Cleaning Foam",purpose:"Washable kitchen surfaces",description:"A foam cleaner for grease, baked-on soil and sticky residue on washable kitchen surfaces. The manufacturer packaging states 98% ingredients of natural origin and that the product contains natural aloe extract.",usage:"Spray foam from about 10 cm away. Rinse or wipe with a damp cloth. For heavy soil, leave for about five minutes before wiping.",cautions:"Do not use on hot surfaces. Test on a small, inconspicuous area before use.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural aloe extract","Cleans grease, baked-on soil and sticky residue","Biodegradable ingredients indicated","98% of the container is made from recycled material"]},
 "dishwasher-tablets":{name:"BIOstar Dishwasher Tablets",purpose:"For dishwashers",description:"Tablet detergent placed one at a time in a dishwasher. Official manufacturer information describes a formula based on ingredients of natural origin, 100% natural-origin soda, active oxygen and a Natural Bioactive Agent. The 100% statement applies only to the soda ingredient, not to the natural-origin percentage of the entire product.",usage:"With dry hands, place one tablet in the dishwasher detergent compartment. Follow the dishwasher manual and product label for the cycle and recommended amount.",cautions:"Do not handle with wet hands. Keep out of reach of children and read the cautions on the product label before use.",features:["Contains 100% natural-origin soda (not the natural-origin percentage of the entire product)","Contains active oxygen","Manufacturer information regarding a Natural Bioactive Agent","No added preservatives or fragrance","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C"]},
 "bathroom-cleaner":{name:"BIOstar Bathroom Cleaning Foam",purpose:"Washable bathroom surfaces",description:"A foam cleaner for water marks and limescale deposits in bathrooms. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Spray onto the surface, leave briefly, then rinse or wipe with a damp cloth. Follow the directions on the product label.",cautions:"Test on a small, inconspicuous area before use and do not use on surfaces excluded by the product label.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","Cleans water marks and limescale deposits"]},
 "shower-cabin-cleaner":{name:"BIOstar Shower Cabin Cleaner",purpose:"Shower cabins",description:"A dedicated cleaner for water marks and limescale deposits on shower cabins. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Spray onto the surface, then rinse or wipe as directed on the product label.",cautions:"Test on a small, inconspicuous area before use and follow the product label.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","For water marks and limescale deposits on shower cabins"]},
 "toilet-gel":{name:"BIOstar Toilet Cleaning Gel",purpose:"Inside toilet bowls",description:"A gel cleaner for water marks and limescale deposits inside toilet bowls. The manufacturer packaging states 98% ingredients of natural origin, natural lavender extract and no added chlorine.",usage:"Apply inside the toilet bowl as directed on the product label, allow the stated contact time, brush and flush.",cautions:"Do not mix with other cleaning products. Keep out of reach of children and follow the product label.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","No added chlorine","Cleans water marks and limescale deposits"]},
 "glass-mirror-cleaner":{name:"BIOstar Glass & Mirror Cleaner",purpose:"Glass and mirrors",description:"A cleaner for marks on glass and mirrors with a streak-free finish. The manufacturer packaging states 98% ingredients of natural origin and that the product contains natural aloe extract and natural vinegar essence.",usage:"Spray onto the surface and wipe with a clean cloth as directed on the product label.",cautions:"Test on a small, inconspicuous area before use and follow the product label.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural aloe extract and natural vinegar essence","Streak-free finish on glass and mirrors"]},
 "universal-cleaner":{name:"BIOstar Universal Cleaner",purpose:"Washable surfaces, including floors",description:"A multi-purpose cleaner for a range of washable surfaces, including floors. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Dilute or apply as directed on the product label according to the surface and level of soil.",cautions:"Check surface compatibility and follow the product label before use.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","For a range of washable surfaces, including floors"]},
 "laundry-capsules":{name:"BIOstar Laundry Capsules",purpose:"White and coloured laundry",description:"A 2-in-1 capsule detergent for white and coloured laundry. The manufacturer packaging states 100% natural plant extracts, natural lavender extract, and no added parabens or microplastics. The 100% statement applies to the plant extracts, not to the entire product.",usage:"With dry hands, place the recommended number of capsules in the drum before adding laundry. Follow the garment care instructions and product label.",cautions:"Do not pierce or handle capsules with wet hands. Keep out of reach of children and follow the product label.",features:["100% natural plant extracts (not a 100% natural-origin product claim)","Contains natural lavender extract","No added parabens or microplastics","2-in-1 capsules for white and coloured laundry"]},
 "eko-dishwasher-tablets":{name:"Ludwik EKO Dishwasher Tablets",purpose:"For dishwashers",description:"All-in-one dishwasher tablets with a baking soda system and biodegradable formula, with cleaning performance from 50°C according to the manufacturer packaging.",usage:"Use one tablet per wash without removing the water-soluble film. Follow the dishwasher manual and product packaging.",cautions:"Do not use on silver, aluminium, crystal, copper or wooden items. Follow the product packaging.",features:["Baking soda system","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C","85% of the packaging is made from recycled material"]},
 "eko-dishwasher-powder":{name:"Ludwik EKO Dishwasher Powder",purpose:"For dishwashers",description:"Dishwasher powder that can be adjusted to the level of soil and water hardness. It uses a baking soda system and biodegradable formula according to the manufacturer packaging.",usage:"Measure according to the level of soil and water hardness, following the product packaging and dishwasher manual.",cautions:"Do not use on silver, aluminium, crystal, copper or wooden items. Follow the product packaging.",features:["Baking soda system","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C","95% of the paper box is made from recycled material"]}
};
const approved=master.products.filter(p=>p.approvalStatus==="approved");
const englishVolume=value=>value.replace(/개입/g," count");
const englishCategory=value=>value==="식기세척기용 세제"?"Dishwasher detergent":value;
const familySlug=p=>p.brandSlug==="ludwik"?p.slug.replace(/-\d+(?:-\d+)?(?:pcs|kg)$/,''):p.slug;
const groups=[...new Map(approved.map(p=>[`${p.brandSlug}/${familySlug(p)}`,approved.filter(x=>`${x.brandSlug}/${familySlug(x)}`===`${p.brandSlug}/${familySlug(p)}`)])).entries()];
const localizeInternalLinks=html => html
  .replace(/(href|action)="\/(?!en\/|\/|#|assets\/|docs\/|api\/|admin\/)/g, '$1="/en/')
  .replace(/href="\/en\/en\//g, 'href="/en/');
const replaceText=(html,replacements)=>Object.entries(replacements)
  .sort(([left],[right])=>right.length-left.length)
  .reduce((value,[ko,en])=>value.replaceAll(ko,en),html);
const mirrorKoreanMain=async(path,replacements={})=>{
  const source=await readFile(new URL(path.replace(/^\//,""),root),"utf8");
  const body=source.match(/<main id="main">([\s\S]*?)<\/main>/)?.[1];
  if(!body)throw new Error(`Unable to read Korean page body: ${path}`);
  return localizeInternalLinks(replaceText(body,replacements));
};
const sharedTranslations={
  "홈":"Home","브랜드":"Brands","제품":"Product","현재 위치":"Current location",
  "회사소개":"About","사업영역":"Business","파트너십":"Partnerships","문의":"Contact",
  "브랜드 스토리":"Brand story","제품 문의하기":"Ask about a product","공식 판매처 보기":"Visit the official store",
  "확인된 제품 정보":"Verified product information","확인된 특징":"Verified features","제품 정보 Q&amp;A":"Product information Q&amp;A",
  "브랜드 페이지":"brand page","브랜드명":"Brand","제품 카테고리":"Category","제품 용도":"Purpose","용량/수량":"Size / quantity",
  "사용 방법":"Directions","주의사항":"Cautions","제조사":"Manufacturer","제조국":"Country of origin","폴란드":"Poland",
  "한국 유통 관계":"Distribution in Korea","공식 제조사 source":"Official manufacturer sources","최종 검토일":"Last reviewed",
  "주요 성분 및 공식 성분 정보":"Ingredient information","용량별 패키지":"Package sizes","개입":" count",
  "공식 자료에서 확인되지 않은 항목은 임의로 표시하지 않습니다. 실제 사용 전 구매 제품의 최신 한글 라벨을 확인하세요.":"Information not verified in official sources is not presented. Always review the latest label on the purchased product before use."
};
const remainingBrandTranslations={
 BIOstar:{
  "공간별 세정 제품":"Cleaning products by use area",
  "주방과 욕실 등 사용하는 공간에 맞춰 제품을 살펴볼 수 있습니다.":"Explore products for the spaces where they are used, including kitchens and bathrooms.",
  "Purpose에 맞춘 제품 구성":"Products organized by purpose",
  "주방세제부터 욕실·다목적 세정제까지 Purpose에 따라 확인할 수 있습니다.":"Browse by purpose, from dishwashing liquid to bathroom and multi-purpose cleaners.",
  "확인 가능한 제품 정보":"Available product information",
  "제품별 Purpose와 용량, 표시된 성분과 사용 정보를 안내합니다.":"Find each product's purpose, size, listed ingredients and usage information.",
  "제품별 사용 안내":"Directions for each product",
  "제품 라벨에 표시된 Directions과 Cautions을 확인한 후 사용하세요.":"Review the directions and cautions on the product label before use.",
  "용도에 맞춘 제품 구성":"Products organized by purpose","주방세제부터 욕실·다목적 세정제까지 용도에 따라 확인할 수 있습니다.":"Browse by purpose, from dishwashing liquid to bathroom and multi-purpose cleaners.","제품별 용도와 용량, 표시된 성분과 사용 정보를 안내합니다.":"Find each product's purpose, size, listed ingredients and usage information.","제품 라벨에 표시된 사용 방법과 주의사항을 확인한 후 사용하세요.":"Review the directions and cautions on the product label before use.",
  "Products by use area 카테고리":"Products by use area categories",
  "주방":"Kitchen","식기세척기":"Dishwasher","욕실":"Bathroom","변기":"Toilet","유리·거울":"Glass & mirrors","다목적":"Multi-purpose","세탁":"Laundry",
  "BIOstar 주방세제 700ml 용기":"BIOstar Dishwashing Liquid 700 ml bottle","주방세제":"Dishwashing Liquid","식기·조리도구 세척":"Washing dishes and cookware",
  "BIOstar 주방 세정 폼 700ml 스프레이 용기":"BIOstar Kitchen Cleaning Foam 700 ml spray bottle","주방 세정 폼":"Kitchen Cleaning Foam","주방 표면":"Kitchen surfaces",
  "BIOstar 식기세척기 세제 50개입 패키지":"BIOstar Dishwasher Tablets 50-count package","식기세척기 세제":"Dishwasher Tablets","50개입":"50 count","식기세척기용":"For dishwashers",
  "BIOstar 욕실 세정 폼 700ml 스프레이 용기":"BIOstar Bathroom Cleaning Foam 700 ml spray bottle","욕실 세정 폼":"Bathroom Cleaning Foam","욕실 타일·세면대·욕조":"Bathroom tiles, sinks and bathtubs",
  "BIOstar 샤워부스 세정제 700ml 스프레이 용기":"BIOstar Shower Cabin Cleaner 700 ml spray bottle","샤워부스 세정제":"Shower Cabin Cleaner","샤워부스·욕실 표면":"Shower cabins and bathroom surfaces",
  "BIOstar 변기 세정 젤 750ml 용기":"BIOstar Toilet Cleaning Gel 750 ml bottle","변기 세정 젤":"Toilet Cleaning Gel","변기 내부 세정":"Cleaning inside toilet bowls",
  "BIOstar 유리·거울 세정제 700ml 스프레이 용기":"BIOstar Glass & Mirror Cleaner 700 ml spray bottle","유리·거울 세정제":"Glass & Mirror Cleaner","유리·거울 표면":"Glass and mirror surfaces",
  "BIOstar 다목적 세정제 800ml 용기":"BIOstar Universal Cleaner 800 ml bottle","다목적 세정제":"Universal Cleaner","생활 공간":"Living spaces","세척 가능한 생활공간 표면":"Washable surfaces in living spaces",
  "BIOstar 2 in 1 세탁 캡슐 32개입 제품 패키지":"BIOstar 2 in 1 Laundry Capsules 32-count package","BIOstar 세탁 캡슐":"BIOstar Laundry Capsules","32개입":"32 count","의류 세탁":"Washing clothes",
  "제조사 공식 정보 기준 천연 유래 성분 97% · 천연 알로에 추출물과 글리세린 함유 · 식기·조리도구의 기름때와 음식물 잔여물 세척 · 제조사가 설명하는 생분해성 성분 기반 포뮬러 · EU Ecolabel Certification(PL/019/009) · 제조사가 설명하는 재활용 가능한 용기":"97% ingredients of natural origin according to official manufacturer information · Contains natural aloe extract and glycerin · Cleans grease and food residue from dishes and cookware · Biodegradable ingredient-based formula, as described by the manufacturer · EU Ecolabel certification (PL/019/009) · Recyclable container, as described by the manufacturer",
  "적당량을 수세미 또는 식기에 덜어 세척한 후 흐르는 물로 충분히 헹궈 주세요. 제품 라벨에 표시된 권장 사용량을 확인해 사용하세요.":"Apply an appropriate amount to a sponge or dish, wash, and rinse thoroughly under running water. Follow the recommended amount on the product label.",
  "Purpose 외에는 사용하지 마시고, 사용 전 제품 라벨에 표시된 Cautions을 확인하세요. 환경에 미치는 영향을 줄이기 위해 권장 사용량을 준수하세요.":"Use only as directed and review the cautions on the product label before use. Follow the recommended amount to reduce environmental impact.",
  "제품 용도 외에는 사용하지 마시고, 사용 전 제품 라벨에 표시된 주의사항을 확인하세요. 환경에 미치는 영향을 줄이기 위해 권장 사용량을 준수하세요.":"Use only as directed and review the cautions on the product label before use. Follow the recommended amount to reduce environmental impact.",
  "천연 알로에 추출물, 글리세린":"Natural aloe extract, glycerin","GRUPA INCO S.A. · 폴란드":"GRUPA INCO S.A. · Poland","주식회사 오름인터내셔널":"OLM International Corp.","제품 정보 Q&amp;A":"Product information Q&amp;A",
  "제조사 공식 정보 기준 천연 유래 성분 97% · 천연 알로에 추출물과 글리세린 함유 · 식기·조리도구의 기름때와 음식물 잔여물 세척 · 제조사가 설명하는 생분해성 성분 기반 포뮬러 · EU Ecolabel 인증(PL/019/009) · 제조사가 설명하는 재활용 가능한 용기":"97% ingredients of natural origin according to official manufacturer information · Contains natural aloe extract and glycerin · Cleans grease and food residue from dishes and cookware · Biodegradable ingredient-based formula, as described by the manufacturer · EU Ecolabel certification (PL/019/009) · Recyclable container, as described by the manufacturer",
  "용도 외에는 사용하지 마시고, 사용 전 제품 라벨에 표시된 주의사항을 확인하세요. 환경에 미치는 영향을 줄이기 위해 권장 사용량을 준수하세요.":"Use only as directed and review the cautions on the product label before use. Follow the recommended amount to reduce environmental impact.",
  "100% 천연 유래 성분 제품인가요?":"Is this product made with 100% ingredients of natural origin?","아닙니다. BIOstar 주방세제는 100% 천연 유래 제품으로 표시된 제품이 아니며, 제조사 공식 정보 기준 천연 유래 성분 비율은 97%입니다.":"No. BIOstar Dishwashing Liquid is not labeled as a product made with 100% ingredients of natural origin. According to official manufacturer information, 97% of its ingredients are of natural origin.",
  "어디에 사용하는 제품인가요?":"What is this product used for?","손설거지할 때 식기와 조리도구의 기름때 및 음식물 잔여물을 세척하는 주방세제입니다.":"It is a dishwashing liquid for cleaning grease and food residue from dishes and cookware when washing by hand.",
  "제조사 기준 천연 유래 성분 98% · 천연 알로에 추출물 함유 · 기름때·눌어붙은 오염·끈적한 때 세정 · 생분해성 성분 표시 · 용기의 98%가 재활용 원료":"98% ingredients of natural origin according to the manufacturer · Contains natural aloe extract · Cleans grease, baked-on soil and sticky residue · Biodegradable ingredients indicated · 98% of the container is made from recycled material",
  "세척할 표면에서 약 10cm 떨어진 거리에서 거품을 분사한 후 헹구거나 젖은 천으로 닦아내세요. 오염이 심한 경우 약 5분간 그대로 둔 다음 닦아내세요.":"Spray foam from about 10 cm away. Rinse or wipe with a damp cloth. For heavy soil, leave for about five minutes before wiping.",
  "뜨거운 표면에는 사용하지 마세요. 사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요.":"Do not use on hot surfaces. Test on a small, inconspicuous area before use.","천연 알로에 추출물":"Natural aloe extract","ECOCERT Ecodetergent 표시":"ECOCERT Ecodetergent marking",
  "100% 천연 유래 소다 함유(제품 전체의 천연 유래 비율을 뜻하지 않음) · 활성 산소 함유 · Natural Bioactive Agent에 대한 제조사 설명 · 보존제 및 향료 무첨가 · 생분해성 포뮬러 · EU Ecolabel 표시 제품 · 50°C부터 세정 성능 발휘":"Contains 100% natural-origin soda (not the natural-origin percentage of the entire product) · Contains active oxygen · Manufacturer information regarding a Natural Bioactive Agent · No added preservatives or fragrance · Biodegradable formula · EU Ecolabel-marked product · Cleaning performance from 50°C",
  "마른 손으로 제품을 꺼내 식기세척기의 세제 투입구에 넣고 작동하세요. 세척 코스와 사용량은 식기세척기 설명서와 제품 라벨의 권장 방법을 확인해 주세요.":"With dry hands, place one tablet in the dishwasher detergent compartment. Follow the dishwasher manual and product label for the cycle and recommended amount.",
  "손이 젖은 상태로 제품을 만지지 마세요. 어린이의 손이 닿지 않는 곳에 보관하고, 제품 라벨에 표시된 Cautions을 확인한 후 사용하세요.":"Do not handle with wet hands. Keep out of reach of children and review the cautions on the product label before use.","천연 유래 소다":"Natural-origin soda",
  "손이 젖은 상태로 제품을 만지지 마세요. 어린이의 손이 닿지 않는 곳에 보관하고, 제품 라벨에 표시된 주의사항을 확인한 후 사용하세요.":"Do not handle with wet hands. Keep out of reach of children and review the cautions on the product label before use.",
  "제품 전체가 100% 천연 유래 성분인가요?":"Is the entire product made with 100% ingredients of natural origin?","아닙니다. 제조사의 100% 표시는 제품에 함유된 소다의 천연 유래 특성을 뜻하며, 제품 전체의 천연 유래 성분 비율을 뜻하지 않습니다.":"No. The manufacturer's 100% statement refers to the natural origin of the soda in the product, not to the percentage of natural-origin ingredients in the entire product.","손설거지용인가요?":"Is it for hand-washing dishes?","아닙니다. 식기세척기의 세제 투입구에 한 개씩 넣어 사용하는 식기세척기용 정제형 세제입니다.":"No. It is a tablet detergent placed one at a time in the dishwasher detergent compartment.",
  "제조사 기준 천연 유래 성분 99% · 천연 라벤더 추출물 함유 · 물때·석회 침전물 세정 · 생분해성 성분 표시 · 용기의 98%가 재활용 원료":"99% ingredients of natural origin according to the manufacturer · Contains natural lavender extract · Cleans water marks and limescale deposits · Biodegradable ingredients indicated · 98% of the container is made from recycled material",
  "사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요. 알루미늄, 대리석, 트래버틴과 석회암 표면에는 사용하지 마세요.":"Test on a small, inconspicuous area before use. Do not use on aluminium, marble, travertine or limestone surfaces.","천연 라벤더 추출물":"Natural lavender extract",
  "제조사 기준 천연 유래 성분 98% · 천연 라벤더 추출물 함유 · 염소 무첨가 · 생분해성 포뮬러 · EU Ecolabel 표시 제품 · 용기의 50%가 재활용 원료":"98% ingredients of natural origin according to the manufacturer · Contains natural lavender extract · No added chlorine · Biodegradable formula · EU Ecolabel-marked product · 50% of the container is made from recycled material",
  "변기 안쪽 가장자리를 따라 적당량을 고르게 바른 후 제품 라벨에 표시된 시간 동안 두세요. 변기용 솔로 문지른 다음 물을 내려 헹궈 주세요.":"Apply an appropriate amount evenly around the inside rim of the toilet bowl and leave it for the time stated on the product label. Brush with a toilet brush, then flush to rinse.","다른 세정제와 혼합하지 마세요. 피부와 눈에 직접 닿지 않도록 주의하고, 어린이의 손이 닿지 않는 곳에 보관하세요.":"Do not mix with other cleaning products. Avoid direct contact with skin and eyes, and keep out of reach of children.",
  "제조사 기준 천연 유래 성분 98% · 천연 알로에 추출물 및 천연 식초 에센스 함유 · 줄무늬 없는 유리·거울 세정 · EU Ecolabel 표시 제품 · 용기의 98%가 재활용 원료":"98% ingredients of natural origin according to the manufacturer · Contains natural aloe extract and natural vinegar essence · Streak-free cleaning for glass and mirrors · EU Ecolabel-marked product · 98% of the container is made from recycled material",
  "세정할 표면에 적당량을 분사한 후 보풀이 없는 마른 천으로 닦아 주세요. 전자기기 화면에는 직접 분사하지 마세요.":"Spray an appropriate amount onto the surface and wipe with a dry, lint-free cloth. Do not spray directly onto electronic screens.","사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요. Purpose 외에는 사용하지 말고 제품 라벨의 Cautions을 확인하세요.":"Test on a small, inconspicuous area before use. Use only as directed and review the cautions on the product label.","천연 알로에 추출물, 천연 식초 에센스":"Natural aloe extract, natural vinegar essence",
  "사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요. 제품 용도 외에는 사용하지 말고 제품 라벨의 주의사항을 확인하세요.":"Test on a small, inconspicuous area before use. Use only as directed and review the cautions on the product label.",
  "사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요. 용도 외에는 사용하지 말고 제품 라벨의 주의사항을 확인하세요.":"Test on a small, inconspicuous area before use. Use only as directed and review the cautions on the product label.",
  "제조사 기준 천연 유래 성분 99% · 천연 라벤더 추출물 함유 · 파라벤 및 색소 무첨가 · 생분해성 성분 표시 · 용기의 50%가 재활용 원료":"99% ingredients of natural origin according to the manufacturer · Contains natural lavender extract · No added parabens or colorants · Biodegradable ingredients indicated · 50% of the container is made from recycled material",
  "넓은 면적을 청소할 때는 제품 라벨의 희석 비율에 맞춰 물에 희석한 후 표면을 닦아 주세요. 심한 오염에는 젖은 천에 소량을 묻혀 닦은 다음 물이나 젖은 천으로 마무리하세요.":"For large areas, dilute in water according to the ratio on the product label, then wipe the surface. For heavy soil, apply a small amount to a damp cloth, wipe, and finish with water or a damp cloth.","사용 전 눈에 잘 띄지 않는 작은 부분에 먼저 시험해 주세요. 보호 처리되지 않은 목재 표면에는 사용하지 마세요.":"Test on a small, inconspicuous area before use. Do not use on untreated wooden surfaces.",
  "천연 식물 추출물 100% 사용(제품 전체의 천연 유래 비율을 뜻하지 않음) · 천연 라벤더 추출물 함유 · 파라벤 및 미세플라스틱 무첨가 · 흰색·유색 의류용 · 생분해성 표시 · EU Ecolabel 표시 제품":"100% natural plant extracts (not the natural-origin percentage of the entire product) · Contains natural lavender extract · No added parabens or microplastics · For white and coloured laundry · Biodegradable formula indicated · EU Ecolabel-marked product",
  "마른 손으로 캡슐을 꺼내 빈 세탁조 안쪽에 먼저 넣은 다음 세탁물을 넣어 주세요. 세탁물의 양과 오염 정도에 따른 사용량은 제품 라벨의 권장 방법을 확인하세요.":"With dry hands, place the capsule in the empty drum before adding laundry. Follow the product label for the recommended amount based on the load size and level of soil.","캡슐을 자르거나 뜯지 마세요. 젖은 손으로 만지지 말고, 어린이의 손이 닿지 않는 건조한 곳에 보관하세요. 의류의 세탁 표시와 제품 라벨의 Cautions을 함께 확인하세요.":"Do not cut or open the capsules. Do not handle with wet hands, and store in a dry place out of reach of children. Review both the garment care instructions and the cautions on the product label.","천연 식물 추출물, 천연 라벤더 추출물":"Natural plant extracts, natural lavender extract",
  "캡슐을 자르거나 뜯지 마세요. 젖은 손으로 만지지 말고, 어린이의 손이 닿지 않는 건조한 곳에 보관하세요. 의류의 세탁 표시와 제품 라벨의 주의사항을 함께 확인하세요.":"Do not cut or open the capsules. Do not handle with wet hands, and store in a dry place out of reach of children. Review both the garment care instructions and the cautions on the product label.",
  "사용할 공간과 목적에 맞는 BIOstar 제품 정보를 안내하는 AI 제품 가이드를 준비하고 있습니다.":"An AI product guide for finding BIOstar product information by use area and purpose is being prepared.","AI 제품 가이드 준비 중":"AI product guide coming soon","BIOstar 제품 안내":"BIOstar product guide"
 },
 Ludwik:{
  "현재 위치":"Current location","생활 방식과 사용량에 맞게 선택할 수 있는 식기세척기용 태블릿과 분말 세제를 소개합니다.":"Discover dishwasher tablets and powder you can choose according to your lifestyle and usage needs.","필요한 사용량에 맞춰 선택할 수 있는 Ludwik EKO 식기세척기용 태블릿 제품군입니다.":"A range of Ludwik EKO Dishwasher Tablets available in quantities to suit your needs.",
  "생활 방식과 사용량에 맞게 선택할 수 있는 Dishwasher tablets과 분말 세제를 소개합니다.":"Discover dishwasher tablets and powder you can choose according to your lifestyle and usage needs.","필요한 사용량에 맞춰 선택할 수 있는 Ludwik EKO Dishwasher tablets 제품군입니다.":"A range of Ludwik EKO Dishwasher Tablets available in quantities to suit your needs.",
  "Ludwik EKO 식기세척기용 태블릿 40개입 패키지":"Ludwik EKO Dishwasher Tablets 40-count package","40개입":"40 count","Ludwik EKO 식기세척기용 태블릿 75개입 패키지":"Ludwik EKO Dishwasher Tablets 75-count package","75개입":"75 count","Ludwik EKO 식기세척기용 태블릿 120개입 패키지":"Ludwik EKO Dishwasher Tablets 120-count package","120개입":"120 count",
  "Ludwik EKO Dishwasher tablets 40개입 패키지":"Ludwik EKO Dishwasher Tablets 40-count package","Ludwik EKO Dishwasher tablets 75개입 패키지":"Ludwik EKO Dishwasher Tablets 75-count package","Ludwik EKO Dishwasher tablets 120개입 패키지":"Ludwik EKO Dishwasher Tablets 120-count package",
  "Ludwik EKO 식기세척기용 분말 세제 1.2kg 패키지":"Ludwik EKO Dishwasher Powder 1.2 kg package","Ludwik EKO 식기세척기용 분말 세제":"Ludwik EKO Dishwasher Powder","식기세척기용 분말 세제로, 오염도와 물의 경도에 맞춰 양을 조절하며 베이킹소다 시스템과 생분해성 포뮬러를 적용했습니다.":"Dishwasher powder with an amount that can be adjusted to the level of soil and water hardness, featuring a baking soda system and biodegradable formula.",
  "태블릿과 분말 세제 모두 제조사 패키지에 베이킹소다 시스템, 생분해성 포뮬러, EU Ecolabel과 50°C부터의 세정 성능이 표시되어 있습니다.":"The manufacturer packaging for both the tablets and powder states a baking soda system, biodegradable formula, EU Ecolabel and cleaning performance from 50°C.","태블릿: 세척 1회당 수용성 필름을 벗기지 않은 태블릿 1개 사용":"Tablets: use one tablet per wash without removing the water-soluble film","태블릿 포장의 85%, 분말 세제 종이 상자의 95%가 재활용 원료":"85% of the tablet packaging and 95% of the powder's paper box are made from recycled material","은·알루미늄·크리스털·구리·나무 제품에는 사용하지 않음":"Do not use on silver, aluminium, crystal, copper or wooden items"
 }
};
const mirroredBrandBody=async(brand)=>{
  const source=await readFile(new URL(`brands/${brand.toLowerCase()}/index.html`,root),"utf8");
  const body=source.match(/<main id="main">([\s\S]*?)<\/main>/)?.[1];
  if(!body)throw new Error(`Unable to read Korean ${brand} page body`);
  const shared={"홈":"Home","브랜드":"Brands","제품 정보 보기":"Product details","제품 상세 정보":"Product details","제품 문의하기":"Ask about a product","공식 판매처 보기":"Visit the official store","판매처 정보 문의하기":"Retailer information","사용 공간":"Use area","제품 용도":"Purpose","용도":"Purpose","제품 특징":"Features","사용 방법":"Directions","주의사항":"Cautions","성분 정보":"Ingredient information","인증":"Certification","제조사·제조국":"Manufacturer · Country of origin","한국 공식 유통":"Official distributor in Korea","정보 확인일":"Last reviewed","제품별 상세 정보":"Product details","제품 목록 보기":"View products"};
  const brandText=brand==="BIOstar"?{
    "일상 공간에 맞춘<br>폴란드 홈케어 브랜드":"Polish homecare<br>for everyday spaces",
    "BIOstar는 폴란드 INCO 그룹이 선보이는 홈케어 브랜드입니다. 주방과 욕실 등 생활공간에 맞춘 다양한 세정 제품을 소개합니다.":"BIOstar is a homecare brand from Poland's INCO Group, with cleaning products designed for kitchens, bathrooms and other everyday spaces.",
    "공간과 제품에 맞춘<br>홈케어 기준":"Homecare guidance<br>by space and product",
    "BIOstar의 제품 구성과 제품별 용도, 표시 정보를 차례로 확인해 보세요.":"Explore the BIOstar range, intended uses and verified label information.",
    "청소가 끝난 뒤에도,<br>남은 유기물 분해를 돕는 미생물":"Microorganisms that help break down<br>residual organic matter after cleaning",
    "BIOstar는 세정 성분과 함께 미생물을 활용하는 제품을 선보입니다. 세정 성분이 표면의 오염을 씻어내는 역할을 하고, 제품에 포함된 미생물은 제조사 설명에 따라 표면에 남은 유기물의 분해를 돕는 방식으로 작용합니다.":"BIOstar offers products that use microorganisms alongside cleaning ingredients. The cleaning ingredients wash soil from surfaces, while the microorganisms in the products work to help break down organic matter left on surfaces, according to the manufacturer.",
    "눈에 보이는 오염을 닦아내는 세정 과정과 미생물이 유기물의 분해를 돕는 과정은 서로 다른 역할입니다.":"The cleaning process that removes visible soil and the process in which microorganisms help break down organic matter perform different roles.",
    "바실러스(Bacillus)는 다양한 환경에서 발견되는 미생물의 한 종류입니다. BIOstar에서는 이러한 미생물을 활용한 청소 원리를 제품 설명에 적용하고 있습니다.":"Bacillus is a type of microorganism found in a variety of environments. BIOstar applies a cleaning principle that uses these microorganisms in its product descriptions.",
    "BIOstar 세정 성분과 미생물 기반 청소 원리 설명 영상":"Video explaining how BIOstar cleaning ingredients and microorganism-based cleaning work",
    "영상을 재생할 수 없는 브라우저입니다. 페이지의 텍스트와 원리 설명 이미지에서 같은 내용을 확인할 수 있습니다.":"Your browser cannot play this video. The same information is available in the page text and explanatory image.",
    "세정과 미생물, 서로 다른 역할":"Cleaning ingredients and microorganisms: different roles",
    "청소할 때 세정 성분은 표면의 때와 오염을 씻어내는 역할을 합니다. BIOstar의 미생물 기반 제품은 여기에 또 하나의 작용 원리를 더합니다.":"During cleaning, cleaning ingredients wash dirt and soil from surfaces. BIOstar's microorganism-based products add another mode of action.",
    "제조사 설명에 따르면 제품에 포함된 미생물은 표면에 남은 유기물의 분해를 돕는 효소를 만들어 작용합니다.":"According to the manufacturer, the microorganisms in the products work by producing enzymes that help break down organic matter left on surfaces.",
    "즉, 세정 성분이 오염을 씻어내는 과정과 미생물이 남은 유기물의 분해를 돕는 과정이 서로 다른 역할을 하는 방식입니다.":"In other words, the cleaning ingredients wash away soil, while the microorganisms help break down the remaining organic matter, with each process performing a different role.",
    "BIOstar 세정 성분과 미생물이 청소 과정에서 서로 다른 역할을 하는 원리 설명":"Explanation of the different roles of BIOstar cleaning ingredients and microorganisms in the cleaning process",
    "제조사 설명에 따른 작용 원리를 이해하기 쉽게 설명한 내용입니다. 실제 작용은 제품과 사용 환경에 따라 달라질 수 있으며, 살균·소독 효과를 의미하지 않습니다.":"This is a simplified explanation of the mode of action described by the manufacturer. Actual results may vary by product and conditions of use, and this does not imply a sanitizing or disinfecting effect.",
    "자료: BIOstar 공식 제품·원료 설명":"Source: Official BIOstar product and ingredient information",
    "공식 판매처 정보를 준비하고 있습니다. 문의 페이지에서 제품 정보를 확인해 주세요.":"Official retailer information is being prepared. Please visit the inquiry page for product information.",
    "BIOstar 제품을 살펴보세요":"Explore BIOstar products","사용하는 공간과 목적에 맞는 제품을 찾고, 제품별 용도와 사용 정보를 확인해 보세요.":"Find products by space and purpose, then review product-specific use information.",
    "사용 공간별 제품":"Products by use area","제품별 상세 정보":"Product details","사용 전 제품 라벨의 최신 표시사항을 함께 확인해 주세요.":"Always review the latest product label before use.",
    "어떤 제품이 필요한지 쉽게 찾아보세요":"Find the product you need","BIOstar 제품 판매처가 궁금하신가요?":"Looking for BIOstar products?"
  }:{
    "폴란드 주방에서 시작해 생활 전반으로 확장된 클리닝 브랜드":"A cleaning brand that grew from Polish kitchens into everyday homecare",
    "1964년부터 이어온 폴란드의 생활 세정 브랜드, Ludwik. 주방에서 시작한 오랜 경험을 바탕으로 일상의 다양한 공간을 위한 홈케어 제품을 선보입니다.":"Ludwik is a Polish homecare brand with experience dating to 1964, offering products for the kitchen and other everyday spaces.",
    "주방에서 시작된 생활 세정의 경험":"Homecare experience that began in the kitchen","1964년 폴란드의 주방에서 시작한 Ludwik는 오랜 시간 생활 속 세정 경험을 축적하며 주방부터 세탁과 홈케어까지 제품 영역을 확장해 왔습니다.":"Ludwik began in a Polish kitchen in 1964 and has built decades of home-cleaning experience, expanding its product range from the kitchen to laundry and homecare.",
    "1964년 시작된 폴란드 생활 세정 브랜드":"A Polish home-cleaning brand established in 1964","주방세제에서 출발해 종합 홈케어로 이어진 경험":"Experience that began with dishwashing liquid and grew into comprehensive homecare",
    "국내에서 만나는 Ludwik EKO 식기세척기 제품":"Ludwik EKO dishwasher products available in Korea",
    "식기세척기용 태블릿":"Dishwasher tablets","제품 상세 정보":"Product details","식기세척기 제품의 공식 표시 정보":"Verified label information for dishwasher products",
    "주방에서 시작해 생활 전반으로":"From the kitchen to everyday homecare","주방세제에서 시작한 Ludwik는 세탁과 다양한 생활 공간을 위한 홈케어 영역으로 제품 경험을 확장해 왔습니다.":"Beginning with dishwashing liquid, Ludwik has expanded its product experience into laundry and homecare for a variety of everyday spaces.",
    "Ludwik 제품을 공식 판매처에서 만나보세요":"Find Ludwik at the official store","오름인터내셔널이 공식적으로 소개하는 Ludwik 제품과 판매 정보를 확인하세요.":"Explore Ludwik products officially introduced by OLM International and find sales information."
  };
  const storyAndExistingEnglish=replaceText(body,brandText);
  const remainingEnglish=replaceText(storyAndExistingEnglish,remainingBrandTranslations[brand]);
  return localizeInternalLinks(replaceText(remainingEnglish,shared));
};
pages.biostar={title:"BIOstar Homecare Products | OLM International",description:"Explore verified information for nine BIOstar homecare products for kitchens, bathrooms, laundry and other spaces.",body:await mirroredBrandBody("BIOstar")};
pages.ludwik={title:"Ludwik | Polish Homecare Brand Since 1964",description:"Discover Ludwik and its EKO dishwasher tablets and powder available in Korea.",body:await mirroredBrandBody("Ludwik")};
pages.brands.body=await mirrorKoreanMain("brands/index.html",{...sharedTranslations,
  "서로 다른 개성,":"Distinct identities,","하나의 신뢰":"One shared trust",
  "오름인터내셔널은 각 브랜드의 고유한 역사와 철학을 존중하며 한국의 일상에 연결합니다.":"OLM International respects each brand's unique history and philosophy and connects it with everyday life in Korea.",
  "1964년 폴란드 주방에서 시작된 생활 세정 브랜드":"A homecare brand founded in a Polish kitchen in 1964",
  "오랜 헤리티지와 폭넓은 홈케어 제품군으로 생활 곳곳의 깨끗함을 제안합니다.":"A long heritage and broad homecare range bring cleanliness to every part of daily life.",
  "일상 공간에 맞춘 폴란드 홈케어 브랜드":"Polish homecare for everyday spaces",
  "BIOstar는 폴란드 INCO 그룹이 선보이는 홈케어 브랜드입니다. 주방과 욕실 등 생활공간에 맞춘 다양한 세정 제품을 소개합니다.":"BIOstar is a homecare brand from Poland's INCO Group, offering cleaning products for kitchens, bathrooms and other everyday spaces.","Ludwik 친환경 식기세척기 세제 40개입":"Ludwik EKO dishwasher tablets, 40 count","BIOstar 다목적 세정제 800ml":"BIOstar universal cleaner, 800 ml"
});
const pageTranslations={
 about:{"좋은 브랜드가":"Helping great brands","더 높이 오를 수 있도록":"rise higher","오름인터내셔널은 브랜드의 본질과 한국 소비자의 일상을 연결하는 공식 파트너입니다.":"OLM International is the official partner connecting the essence of brands with everyday life in Korea.","빠른 유통보다":"Beyond quick distribution,","오래가는 브랜드를 만듭니다":"we build enduring brands","제품을 소개하는 데서 그치지 않고, 브랜드가 지켜온 가치와 한국 시장의 맥락을 함께 이해합니다. 분명한 포지셔닝과 책임 있는 채널 운영으로 지속 가능한 성장을 지향합니다.":"We go beyond introducing products to understand both the values a brand protects and the Korean market context. Clear positioning and responsible channel operation support sustainable growth.","함께 쌓아갈 이정표":"Milestones we will build together","공식 파트너 브랜드 집중":"Focus on official partner brands","Ludwik와 BIOstar의 가치와 제품을 한국 소비자에게 일관되게 소개합니다.":"We consistently introduce the value and products of Ludwik and BIOstar to Korean consumers.","생활용품 브랜드 성장 기반 강화":"Strengthen the foundation for homecare brand growth","브랜드와 고객을 잇는 콘텐츠, 마케팅, 유통 접점을 정교하게 확장합니다.":"We expand content, marketing and distribution touchpoints connecting brands and customers.","파트너십·인증":"Partnerships and certifications","공식 파트너십 증빙과 제품별 인증 자료는 확인된 공식 자료를 기준으로 이 영역에 게시합니다.":"Verified official partnership and product certification materials will be published here.","공식 증빙 자료 업데이트 예정 · 제품 인증은 해당 제품 단위로 표시":"Official documentation coming soon · Certifications are shown per product","회사정보":"Company information","회사명":"Company","주식회사 오름인터내셔널":"OLM International Corp.","이메일":"Email","대표 연락처":"Phone","주소":"Address","경기도 수원시 팔달구 효원로249번길 46-15, 5층 85호":"5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea"},
 business:{"발굴에서 안착까지,":"From discovery to market entry,","하나의 흐름으로":"one connected process","해외 브랜드가 한국 시장에서 자신의 가치를 선명하게 전하고 성장하도록 전 과정을 연결합니다.":"We connect every stage so international brands can communicate their value and grow in Korea.","오름인터내셔널 사업 역량":"OLM International capabilities","해외 브랜드 소싱":"International brand sourcing","시장 가능성과 브랜드 철학, 제품 경쟁력을 함께 살펴 좋은 파트너를 발굴합니다.":"We identify strong partners by reviewing market potential, brand philosophy and product competitiveness.","국내 마케팅·브랜드 빌딩":"Korean marketing and brand building","한국 고객에게 닿는 언어와 콘텐츠로 브랜드의 가치를 일관되게 전달합니다.":"We consistently communicate brand value through language and content that reaches Korean customers.","온라인 유통채널 운영":"Online distribution channel operation","고객 접점과 구매 여정을 관리하며 신뢰할 수 있는 공식 판매 경험을 만듭니다.":"We manage touchpoints and purchase journeys to create a trusted official sales experience.","한국 시장 안착을 위한 흐름":"A path to establishing your brand in Korea","브랜드와 시장의 가능성을 발견합니다":"Discover brand and market potential","브랜드가 지켜온 가치와 제품의 차별점을 이해하고, 한국 소비자와 시장 환경에 적합한 진입 가능성을 검토합니다.":"We understand brand values and product differentiation, then assess fit with Korean consumers and the market.","브랜드·제품 분석":"Brand and product analysis","국내 시장 적합성 검토":"Korean market fit review","소비자와 경쟁환경 이해":"Consumer and competitive landscape","한국 시장에 맞는 기반을 설계합니다":"Build the foundation for Korea","시장 안착 이후의 성장을 함께 만듭니다":"Grow together after launch","브랜드 정체성을 유지하면서 한국 소비자에게 전달할 포지셔닝, 콘텐츠와 판매채널 운영 방향을 구체화합니다.":"Preserve brand identity while defining positioning, content and sales-channel operations for Korean consumers.","브랜드 현지화":"Brand localization","콘텐츠와 커뮤니케이션":"Content and communication","판매채널 전략 수립":"Sales-channel strategy","온라인 유통채널 운영과 고객 반응을 지속적으로 살피며 브랜드가 한국 시장에서 장기적으로 성장할 기반을 강화합니다.":"We continuously monitor online channels and customer response to strengthen long-term growth in Korea.","온라인 채널 운영":"Online channel operation","고객 반응과 성과 확인":"Customer response and performance review","장기 성장 기반 강화":"Strengthen long-term growth"},
 partnership:{"브랜드 기준을 지키며":"Protecting brand standards","한국 시장과 연결합니다":"while connecting with Korea","오름인터내셔널은 단순한 유통을 넘어 브랜드의 목소리와 한국 소비자의 기대 사이를 연결합니다. 시장 이해, 현지화, 채널 운영을 하나의 팀처럼 함께합니다.":"Beyond distribution, OLM International connects brand voices with Korean consumer expectations through market understanding, localization and channel operation.","주요 온라인 유통채널":"Major online retail channels","브랜드의 특성과 국내 판매 전략에 맞는 유통채널을 검토하고, 한국 소비자와 효과적으로 연결될 수 있도록 지원합니다.":"We review channels suited to each brand and sales strategy to connect effectively with Korean consumers.","국내 주요 온라인 유통채널 로고":"Major Korean online retail channel logos","지원 범위":"How we support you","시장 맥락과 고객 접점을 고려한 진입 방향을 함께 설계합니다.":"We shape market entry around the market context and customer journey.","브랜드 아이덴티티를 존중하는 현지 콘텐츠와 커뮤니케이션을 구축합니다.":"We build local content and communication that respect brand identity.","공식 판매채널을 운영하고 지속적인 성장을 위한 기반을 관리합니다.":"We operate official sales channels and manage a foundation for continued growth.","협업 절차":"How we collaborate","브랜드와 제품, 한국 시장에서의 목표를 공유합니다.":"Share the brand, products and goals for Korea.","제품군과 시장 적합성, 협업 범위를 함께 검토합니다.":"Review the range, market fit and scope together.","현지화, 채널, 마케팅 실행 계획을 구체화합니다.":"Define localization, channel and marketing plans.","론칭 이후 성과를 살피며 장기적인 성장을 만듭니다.":"Review performance after launch and build long-term growth.","영문 제안 자료와 상세 협업 문의는 연락처를 통해 요청해 주세요.":"Contact us for an English proposal and detailed partnership discussion.","파트너십 문의":"Partnership inquiry"},
 contact:{"함께 이야기해 주세요":"Let's start a conversation","문의 목적을 선택해 남겨 주시면 담당 범위에 따라 안내할 수 있도록 준비하겠습니다.":"Select the purpose of your inquiry and share the details with our team.","연락처 안내":"Get in touch","회사명":"Company","주식회사 오름인터내셔널":"OLM International Corp.","이메일":"Email","대표 연락처":"Phone","주소":"Address","경기도 수원시 팔달구 효원로249번길 46-15, 5층 85호":"5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea","문의 유형":"Inquiry type","선택해 주세요":"Please select","소비자 문의":"Consumer inquiry","유통·입점 문의":"Distribution inquiry","해외 브랜드 파트너십 문의":"International brand partnership","이름 / 회사명":"Name / Company","연락처":"Phone","선택 사항":"Optional","문의 내용":"Message","문의 응대를 위한 개인정보 수집에 동의합니다.":"I agree to the collection of personal information required to respond to this inquiry.","문의 내용 확인":"Review inquiry","문의 내용을 입력해 주세요.":"Please complete the inquiry form."}
};
for(const id of ["about","business","partnership","contact"]){pages[id].body=await mirrorKoreanMain(`${id}/index.html`,{...sharedTranslations,...pageTranslations[id]});}
pages["ai-clean-care"].body=await mirrorKoreanMain("ai-clean-care/index.html",{...sharedTranslations,
  "AI 클린케어":"AI Clean Care","세제에 관한 모든 질문,":"Questions about detergents?","제품 선택부터 성분, 사용법, 광고 문구 확인까지. 확인된 제품 정보와 세정 지식을 바탕으로 답변합니다.":"Get guidance on product selection, ingredients, directions and advertising claims based on verified product information and cleaning knowledge.",
  "무엇을 확인해 볼까요?":"What would you like to check?","세제, 성분, 사용 공간 또는 광고 문구에 대해 질문해 주세요.":"Ask about a product, ingredient, use area or advertising statement.","개인정보나 민감한 정보는 입력하지 마세요.":"Do not enter personal or sensitive information.","AI에게 질문하기":"Ask AI","추천 질문":"Suggested questions","AI 답변":"AI response","더 자세히 알아보기":"Explore in more detail","더 자세히 알아본 내용":"Detailed response",
  "기름기가 많은 식기를 씻을 때 어떤 제품이 적합한가요?":"Which product is suitable for greasy dishes?","욕실 물때에 주방세제를 사용해도 되나요?":"Can dishwashing liquid be used on bathroom limescale?","천연 유래 성분이라는 말은 무엇을 의미하나요?":"What does naturally derived mean?","유기농 세제라는 광고를 그대로 믿어도 되나요?":"How should I assess an organic detergent claim?","세탁 캡슐은 어떻게 사용해야 하나요?":"How should laundry capsules be used?","BIOstar와 일반 세정제의 차이를 알려주세요.":"How does BIOstar differ from conventional cleaners?","이 답변은 Ludwik와 BIOstar의 대한민국 공식 파트너인 오름인터내셔널이 제공하는 제품정보를 우선 검토합니다.":"This response prioritizes product information provided by OLM International, the official Korean partner of Ludwik and BIOstar."
});
const organization={"@type":"Organization","@id":`${site}/#organization`,name:"OLM International Corp.",url:`${site}/`,email:"khs@olm.kr"};
for(const [id,page] of Object.entries(pages)){
 const path=id==="home"?"/en/":id==="biostar"||id==="ludwik"?`/en/brands/${id}/`:`/en/${id}/`;
 const folder=id==="home"?new URL("en/",root):new URL(path.slice(1),root); await mkdir(folder,{recursive:true});
 const jsonLd={"@context":"https://schema.org","@graph":[organization,{"@type":"WebPage",url:`${site}${path}`,name:page.title,description:page.description,inLanguage:"en"}]};
 await writeFile(new URL("index.html",folder),layout({path,id,title:page.title,description:page.description,body:page.body,jsonLd}));
}
for(const [key,items] of groups){
 const slug=key.split('/')[1],en=productEnglish[slug],p=items[0],path=`/en/brands/${key}/`,volumes=items.map(x=>englishVolume(x.volume)).join(" · ");
 const facts=[["Brand",p.brand],["Category",englishCategory(p.category)],["Purpose",en.purpose],["Size / quantity",volumes],["Directions",en.usage],["Cautions",en.cautions],["Manufacturer",p.manufacturer||"Not stated in the reviewed source"],["Country of origin",p.countryOfOrigin==="폴란드"?"Poland":p.countryOfOrigin],["Korean distributor",p.distributor?"OLM International Corp.":"Not stated in the reviewed source"],["Last reviewed",p.lastReviewedAt]];
 const productReplacements={...sharedTranslations,
   [p.name.replace(/\s+\d+개입$/,'')]:en.name,
   [p.description]:en.description,[p.purpose]:en.purpose,[p.usage]:en.usage,[p.cautions]:en.cautions,
   "제품과 브랜드:":"Product and brand:",
   [`이 제품은 ${p.brand} 브랜드의 ${p.category} 제품이며, ${p.manufacturer}가 제조합니다. 한국 유통 관계는 아래 확인된 제품 정보에서 안내합니다.`]:`This ${p.category} product is made by ${p.manufacturer} for the ${p.brand} brand. Distribution details are provided below.`,
   "주식회사 오름인터내셔널가 한국에서 공식 유통합니다.":"Officially distributed in Korea by OLM International Corp.",
   "NEEDS REVIEW — OLM의 법적·계약상 유통 지위 확인 필요":"NEEDS REVIEW — OLM's legal and contractual distribution status requires verification",
   "제조사 제품 패키지에서 확인한 주요 성분 특징입니다. 전체 성분은 구매 제품의 최신 한글 표시사항을 확인해 주세요.":"Key ingredient information verified on the manufacturer packaging. Check the latest product label for the complete ingredients.",
   "제조사 제품 패키지에서 확인한 주요 성분 특징입니다.":"Key ingredient information verified on the manufacturer packaging.",
   ...Object.fromEntries((p.features||[]).map((value,index)=>[value,en.features[index]||value]))
 };
 const body=await mirrorKoreanMain(`brands/${key}/index.html`,productReplacements);
 const canonical=`${site}${path}`;
 const jsonLd={"@context":"https://schema.org","@graph":[organization,{"@type":"WebPage",url:canonical,name:en.name,description:en.description,inLanguage:"en"},{"@type":"Product",name:en.name,description:en.description,image:items.map(x=>`${site}${x.images[0].src}`),brand:{"@type":"Brand",name:p.brand},manufacturer:p.manufacturer?{"@type":"Organization",name:p.manufacturer}:undefined,category:englishCategory(p.category),url:canonical}]};
 const folder=new URL(path.slice(1),root);await mkdir(folder,{recursive:true});await writeFile(new URL("index.html",folder),layout({path,id:"brands",title:`${en.name} | OLM International`,description:en.description,body,jsonLd}));
}
export const englishRoutes=["/en/",...Object.keys(pages).filter(x=>x!=="home").map(id=>id==="biostar"||id==="ludwik"?`/en/brands/${id}/`:`/en/${id}/`),...groups.map(([key])=>`/en/brands/${key}/`)];
