import { mkdir, readFile, writeFile } from "node:fs/promises";
import { renderLanguageSwitcher } from "../src/components/language-switcher.js";
import { renderMetadata } from "../src/seo/metadata.js";

const root=new URL("../",import.meta.url), site="https://olm.kr";
const master=JSON.parse(await readFile(new URL("assets/data/product-master.json",root),"utf8"));
const logoPath="/docs/source-images/ChatGPT Image 2026년 8월 22일 오후 01_09_56.png";
const nav=[['about','About'],['brands','Brands'],['business','Business'],['partnership','Partnerships'],['ai-clean-care','AI Clean Care'],['contact','Contact']];
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const koPath=path=>path.replace(/^\/en/,"")||"/";
const header=(current,path)=>`<a class="skip-link" href="#main">Skip to content</a><header class="header"><div class="container header-inner"><a class="logo"${current==="home"?' data-home-header-logo':''} href="/en/"><img src="${logoPath}" width="320" height="120" alt="OLM International"></a><button class="menu-button" id="menu-open" aria-controls="primary-nav" aria-expanded="false"><span></span><span></span><span></span><span class="sr-only">Open menu</span></button><nav class="nav" id="primary-nav" aria-label="Primary navigation"><button class="menu-close" id="menu-close" aria-label="Close menu">✕</button>${nav.map(([id,label])=>`<a href="/en/${id}/"${current===id?' aria-current="page"':''}>${label}</a>`).join("")}${renderLanguageSwitcher({currentLocale:"en",koreanPath:koPath(path),englishPath:path})}</nav></div></header>`;
const footer=`<footer class="footer"><div class="container"><div class="footer-top"><a class="logo" href="/en/"><img src="${logoPath}" width="320" height="120" alt="OLM International"></a><div class="footer-info"><span><b>Company</b> OLM International Corp.</span><span><b>Email</b> <a href="mailto:khs@olm.kr">khs@olm.kr</a></span><span><b>Phone</b> <a href="tel:07087799669">070-8779-9669</a></span><span><b>Address</b> 5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea</span></div></div><div class="footer-bottom">© 2026 OLM International Corp. All rights reserved. &nbsp; <a href="/en/contact/">Contact</a><a class="footer-admin" href="/admin/ai-clean-care/">Admin</a></div></div></footer>`;
const alternates=path=>({ko:`${site}${koPath(path)}`,en:`${site}${path}`});
const layout=({path,id,title,description,body,jsonLd})=>{const metadata={lang:"en",title,description,canonical:`${site}${path}`,alternates:alternates(path),openGraph:{title,description,locale:"en_US",url:`${site}${path}`,image:`${site}/assets/common/og/olm-og.png`}};return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">${renderMetadata(metadata)}<link rel="icon" href="/assets/common/icons/favicon.png" type="image/png"><link rel="stylesheet" href="/assets/css/style.css">${jsonLd?`<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<","\\u003c")}</script>`:""}</head><body>${header(id,path)}<main id="main">${body}</main>${footer}<script src="/assets/data/site-data.js"></script><script src="/assets/js/main.js"></script></body></html>`};
const hero=(label,title,lead)=>`<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/en/">Home</a> / ${label}</div><span class="eyebrow">${label}</span><h1 class="display">${title}</h1><p class="lead">${lead}</p></div></section>`;
const pages={
 home:{title:"OLM International | Connecting European Homecare Brands with Korea",description:"Meet OLM International and the Ludwik and BIOstar homecare brands in Korea.",body:`<section class="hero"><div class="hero-background" aria-hidden="true"></div><div class="hero-overlay" aria-hidden="true"></div><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Official partner in Korea</span><h1 class="display">European premium homecare brands,<br>Korea’s official partner</h1><p>OLM International officially introduces Ludwik and BIOstar to Korea.</p><div class="btn-row"><a class="btn btn-primary" href="/en/brands/">Explore our brands</a><a class="btn btn-light" href="https://smartstore.naver.com/olmmall" target="_blank" rel="noopener noreferrer">Visit the official store</a></div></div></div><button class="hero-scroll-cue" type="button" aria-label="Go to the next section" aria-controls="home-introduction"><span>SCROLL</span><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg></button></section>
<section class="trust-strip" id="home-introduction" tabindex="-1" aria-label="OLM International commitment"><div class="container trust-inner"><strong>Bringing brand value into everyday life in Korea</strong><span>Official partnership · Local market expertise · Sustainable growth</span></div></section>
<section class="section brand-showcase reveal" aria-labelledby="brands-title"><div class="container"><header class="section-heading"><span class="eyebrow">OUR BRANDS</span><h2 class="title" id="brands-title">European homecare brands for everyday life in Korea</h2><p class="lead">OLM International accurately communicates the brand values and product information of Ludwik and BIOstar to Korean consumers.</p></header><div class="brand-editorial">
<a class="brand-panel brand-panel-ludwik" href="/en/brands/ludwik/"><div class="brand-copy"><span class="brand-label">LUDWIK · POLAND · SINCE 1964</span><h3>Polish homecare<br>since 1964</h3><p>A household cleaning brand that began in the Polish kitchen and expanded into laundry and homecare.</p><ul aria-label="Ludwik product categories"><li>Kitchen</li><li>Dishwasher</li><li>Laundry</li><li>Homecare</li></ul><span class="panel-cta">Explore Ludwik <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-ludwik"><img src="/docs/source-images/ludwik-eko-dishwasher-tablets-120pcs.png" width="2724" height="3587" alt="Ludwik EKO dishwasher tablets 120-count package" loading="lazy" decoding="async"><img src="/docs/source-images/ludwik-eko-dishwasher-powder-1-2kg.png" width="2362" height="3154" alt="Ludwik EKO dishwasher powder 1.2 kg package" loading="lazy" decoding="async"></div></a>
<a class="brand-panel brand-panel-biostar" href="/en/brands/biostar/"><div class="brand-copy"><span class="brand-label">BIOSTAR · POLAND</span><h3>Everyday cleaning<br>by space and purpose</h3><p>A homecare brand from Poland’s INCO Group, offering cleaning products for kitchens, bathrooms and everyday spaces.</p><ul aria-label="BIOstar product categories"><li>Kitchen care</li><li>Bathroom care</li><li>Multi-purpose care</li><li>Dishwasher care</li></ul><span class="panel-cta">Explore BIOstar <b aria-hidden="true">→</b></span></div><div class="brand-products brand-products-biostar"><img src="/docs/source-images/biostar-kitchen-cleaner-700ml.png" width="854" height="2270" alt="BIOstar kitchen cleaning foam 700 ml bottle" loading="lazy" decoding="async"><img src="/docs/source-images/biostar-bathroom-cleaner-700ml.png" width="854" height="2270" alt="BIOstar bathroom cleaning foam 700 ml bottle" loading="lazy" decoding="async"></div></a>
</div></div></section>
<section class="section product-guide reveal" aria-labelledby="guide-title"><div class="container guide-layout"><div><span class="eyebrow">PRODUCT GUIDE</span><h2 class="title" id="guide-title">Find the product<br>you need with ease</h2></div><div class="guide-copy"><p>Explore Ludwik and BIOstar products by space and purpose. Our AI product guide provides information about product uses and directions.</p><small>AI product guide available</small><nav aria-label="Product guide links"><a href="/en/brands/ludwik/">View Ludwik products <span aria-hidden="true">→</span></a><a href="/en/brands/biostar/">View BIOstar products <span aria-hidden="true">→</span></a><a href="/en/ai-clean-care/">Ask about a product <span aria-hidden="true">→</span></a></nav></div></div></section>
<section class="section market-partner reveal" aria-labelledby="market-title"><div class="container"><header class="section-heading"><span class="eyebrow">KOREA MARKET PARTNER</span><h2 class="title" id="market-title">Connecting brand potential<br>with growth in Korea</h2><p class="lead">OLM International supports international homecare brands from market review through brand operations and distribution channel management.</p></header><ol class="market-flow"><li class="reveal-step"><span>01</span><div><h3>Brand sourcing and market review</h3><p>We evaluate each brand and product for its fit with the Korean market and consumers.</p></div></li><li class="reveal-step"><span>02</span><div><h3>Localization and brand building</h3><p>We design content and communication that accurately convey brand value to Korean consumers.</p></div></li><li class="reveal-step"><span>03</span><div><h3>Channel operation and growth</h3><p>We operate local online channels and support sustainable growth based on market response.</p></div></li></ol><div class="partner-callout"><div><h3>We are looking for brands ready to grow in Korea</h3><p>We welcome proposals from international homecare brands seeking market entry and long-term operations in Korea.</p></div><a class="link-arrow" href="/en/partnership/">Explore partnerships →</a></div></div></section>
<section class="section-sm retailer-status reveal" id="retailers" aria-labelledby="retailers-title"><div class="container retailer-layout"><div><span class="eyebrow">OFFICIAL RETAILERS</span><h2 id="retailers-title">Official sales channels</h2><p>Verified official sales channels will be listed here as they become available.</p><strong>Sales channel updates coming soon</strong></div><nav aria-label="Sales channel links"><a href="/en/ai-clean-care/">Ask about a product →</a><a href="/en/brands/">Explore our brands →</a></nav></div></section>`},
 about:{title:"About | OLM International",description:"Learn how OLM International connects international homecare brands with the Korean market.",body:hero("About","We understand brands.<br>We build lasting growth.","OLM International connects brands and consumers with a long-term view of the Korean market.")+`<section class="section"><div class="container split"><div><span class="eyebrow">WHO WE ARE</span><h2 class="title">A partner that connects brand value with the Korean market</h2></div><div><p class="lead">We go beyond distribution. We review the market, localize communication and operate sales channels so that each brand can meet Korean consumers in the right way.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">OUR APPROACH</span><div class="feature-row"><article><h3>Understand</h3><p>We begin with the brand, product and market context.</p></article><article><h3>Connect</h3><p>We shape local content and consumer touchpoints while preserving brand identity.</p></article><article><h3>Grow</h3><p>We manage channels and support sustainable, long-term market development.</p></article></div></div></section>`},
 brands:{title:"Brands | OLM International",description:"Explore Ludwik and BIOstar, the homecare brands introduced in Korea by OLM International.",body:hero("Brands","Brands for everyday care","Discover the homecare brands and verified product information introduced by OLM International.")+`<section class="section brand-showcase"><div class="container"><div class="brand-editorial"><a class="brand-panel brand-panel-ludwik" href="/en/brands/ludwik/"><div class="brand-copy"><span class="brand-label">LUDWIK · POLAND</span><h3>Homecare experience<br>since 1964</h3><p>A Polish cleaning brand whose experience began in the kitchen and expanded across everyday homecare.</p><span class="panel-cta">Explore Ludwik →</span></div></a><a class="brand-panel brand-panel-biostar" href="/en/brands/biostar/"><div class="brand-copy"><span class="brand-label">BIOSTAR · POLAND</span><h3>Cleaning solutions<br>for everyday spaces</h3><p>A GRUPA INCO homecare brand with products for kitchens, bathrooms and other household spaces.</p><span class="panel-cta">Explore BIOstar →</span></div></a></div></div></section>`},
 business:{title:"Business | OLM International",description:"OLM International supports brand sourcing, localization, brand building and online distribution in Korea.",body:hero("Business","From brand sourcing<br>to market growth","We connect international homecare brands with the Korean market through an integrated operating approach.")+`<section class="section"><div class="container"><div class="cap-grid"><article class="cap-item"><span class="num">01</span><h3>Brand sourcing</h3><p>We review products, positioning and fit with the Korean market.</p></article><article class="cap-item"><span class="num">02</span><h3>Localization &amp; brand building</h3><p>We develop market communication that respects the brand’s identity.</p></article><article class="cap-item"><span class="num">03</span><h3>Channel operation</h3><p>We operate online sales channels and manage consumer touchpoints.</p></article></div></div></section>`},
 partnership:{title:"Korea Market Partnerships | OLM International",description:"Partner with OLM International to review and develop opportunities for homecare brands in Korea.",body:hero("Partnership","Your trusted partner<br>for the Korean market","We help international homecare brands enter, connect and grow in Korea with a long-term perspective.")+`<section class="section"><div class="container split"><div><span class="eyebrow">LOCAL EXPERTISE</span><h2 class="title">Protecting brand standards while connecting with Korea</h2></div><div><p class="lead">We work as one team across market understanding, localization and channel operation.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">OUR SUPPORT</span><div class="feature-row"><article><h3>Market entry</h3><p>We shape an entry direction around the market and customer journey.</p></article><article><h3>Brand building</h3><p>We build local content and communication that respect brand identity.</p></article><article><h3>Channel operation</h3><p>We operate official sales channels and manage the foundation for continued growth.</p></article></div></div></section><section class="section dark partnership-cta"><div class="container b2b"><div><h2 class="title">Let’s build your brand’s<br>next chapter in Korea.</h2></div><a class="btn btn-light" href="/en/contact/?type=partnership">Partnership inquiry</a></div></section>`},
 contact:{title:"Contact | OLM International",description:"Contact OLM International about products, distribution and international brand partnerships.",body:hero("Contact","Let’s start a conversation","Select the purpose of your inquiry and share the details with our team.")+`<section class="section"><div class="container contact-grid"><aside><span class="eyebrow">CONTACT INFORMATION</span><h2 class="title">Get in touch</h2><ul class="contact-list"><li><b>Company</b><br>OLM International Corp.</li><li><b>Email</b><br><a href="mailto:khs@olm.kr">khs@olm.kr</a></li><li><b>Phone</b><br><a href="tel:07087799669">070-8779-9669</a></li><li><b>Address</b><br>5F, Unit 85, 46-15 Hyowon-ro 249beon-gil, Paldal-gu, Suwon-si, Gyeonggi-do, Republic of Korea</li></ul></aside><div><form id="contact-form"><div class="form-grid"><div class="field"><label for="type">Inquiry type</label><select id="type" name="type" required><option value="">Please select</option><option>Consumer inquiry</option><option>Distribution inquiry</option><option>International brand partnership</option></select></div><div class="field"><label for="name">Name / Company</label><input id="name" name="name" autocomplete="name" maxlength="120" required></div><div class="field"><label for="email">Email</label><input id="email" name="email" type="email" autocomplete="email" maxlength="254" required></div><div class="field"><label for="phone">Phone <span class="sr-only">Optional</span></label><input id="phone" name="phone" autocomplete="tel" maxlength="60"></div><div class="field full"><label for="message">Message</label><textarea id="message" name="message" maxlength="5000" required></textarea></div><div class="field full"><label><input type="checkbox" required> I agree to the collection of personal information required to respond to this inquiry.</label></div></div><button class="btn btn-primary" type="submit">Review inquiry</button><p class="form-status" id="form-status" tabindex="-1" role="status">Please complete the inquiry form.</p></form></div></div></section>`},
 'ai-clean-care':{title:"AI Clean Care | OLM International",description:"Ask about product selection, ingredients, directions and advertising claims using verified product information.",body:`<section class="ai-hero"><div class="container ai-hero-grid"><div><nav class="breadcrumb"><a href="/en/">Home</a> / AI Clean Care</nav><span class="eyebrow">AI CLEAN CARE</span><h1 class="display">Questions about detergents?<br>Ask AI Clean Care.</h1><p class="lead">Get guidance based on verified product information and cleaning knowledge.</p></div></div></section><section class="section ai-workspace"><div class="container ai-layout"><div class="ai-main"><form id="ai-care-form" class="ai-question-card"><div class="ai-card-index">01 · ASK</div><label for="ai-question">What would you like to check?</label><textarea id="ai-question" name="question" maxlength="1200" rows="5" required placeholder="Ask about a product, ingredient, area of use or advertising statement."></textarea><div class="ai-form-meta"><span>Do not enter personal or sensitive information.</span><span id="ai-char-count">0 / 1,200</span></div><button class="btn btn-primary" type="submit">Ask AI <span aria-hidden="true">→</span></button></form><section class="ai-result" id="ai-result" hidden tabindex="-1"><div class="ai-section-heading"><span>02</span><h2>AI response</h2></div><div id="ai-status" class="ai-status" role="status" aria-live="polite"></div><div id="ai-answer"></div><button class="btn ai-deep-button" id="ai-deep-button" type="button" hidden>Explore in more detail →</button></section><section class="ai-deep-result" id="ai-deep-result" hidden tabindex="-1"><div class="ai-section-heading"><span>03</span><h2>Detailed response</h2></div><div id="ai-deep-status" class="ai-status" role="status"></div><div id="ai-deep-answer"></div></section></div></div></section>`}
};
const productEnglish={
 "dishwashing-liquid":{name:"BIOstar Dishwashing Liquid",purpose:"Hand-washing dishes and cookware",description:"A hand dishwashing liquid made with a formula containing 97% ingredients of natural origin according to official manufacturer information. It contains natural aloe extract and glycerin and cleans grease and food residue from dishes and cookware.",usage:"Apply an appropriate amount to a sponge or dish, wash, and rinse thoroughly under running water. Follow the recommended amount on the product label.",cautions:"Use only as directed and review the cautions on the product label before use. Follow the recommended amount to reduce environmental impact.",features:["97% ingredients of natural origin according to official manufacturer information","Contains natural aloe extract and glycerin","Cleans grease and food residue from dishes and cookware","Biodegradable ingredient-based formula, as described by the manufacturer","EU Ecolabel certification (PL/019/009)","Recyclable container, as described by the manufacturer"]},
 "kitchen-cleaner":{name:"BIOstar Kitchen Cleaning Foam",purpose:"Washable kitchen surfaces",description:"A foam cleaner for grease, baked-on soil and sticky residue on washable kitchen surfaces. The manufacturer packaging states 98% ingredients of natural origin and that the product contains natural aloe extract.",usage:"Spray foam from about 10 cm away. Rinse or wipe with a damp cloth. For heavy soil, leave for about five minutes before wiping.",cautions:"Do not use on hot surfaces. Test on a small, inconspicuous area before use.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural aloe extract","Cleans grease, baked-on soil and sticky residue","Biodegradable ingredients indicated","98% of the container is made from recycled material"]},
 "dishwasher-tablets":{name:"BIOstar Dishwasher Tablets",purpose:"For dishwashers",description:"Tablet detergent placed one at a time in a dishwasher. Official manufacturer information describes a formula based on ingredients of natural origin, 100% natural-origin soda, active oxygen and a Natural Bioactive Agent. The 100% statement applies only to the soda ingredient, not to the natural-origin percentage of the entire product.",usage:"With dry hands, place one tablet in the dishwasher detergent compartment. Follow the dishwasher manual and product label for the cycle and recommended amount.",cautions:"Do not handle with wet hands. Keep out of reach of children and read the cautions on the product label before use.",features:["Contains 100% natural-origin soda (not the natural-origin percentage of the entire product)","Contains active oxygen","Manufacturer information regarding a Natural Bioactive Agent","No added preservatives or fragrance","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C"]},
 "bathroom-cleaner":{name:"BIOstar Bathroom Cleaning Foam",purpose:"Washable bathroom surfaces",description:"A foam cleaner for water marks and limescale deposits in bathrooms. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Spray onto the surface, leave briefly, then rinse or wipe with a damp cloth. Follow the directions on the product label.",cautions:"Test on a small, inconspicuous area before use and do not use on surfaces excluded by the product label.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","Cleans water marks and limescale deposits"]},
 "shower-cabin-cleaner":{name:"BIOstar Shower Cabin Cleaner",purpose:"Shower cabins",description:"A dedicated cleaner for water marks and limescale deposits on shower cabins. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Spray onto the surface, then rinse or wipe as directed on the product label.",cautions:"Test on a small, inconspicuous area before use and follow the product label.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","For water marks and limescale deposits on shower cabins"]},
 "toilet-gel":{name:"BIOstar Toilet Cleaning Gel",purpose:"Inside toilet bowls",description:"A gel cleaner for water marks and limescale deposits inside toilet bowls. The manufacturer packaging states 98% ingredients of natural origin, natural lavender extract and no added chlorine.",usage:"Apply inside the toilet bowl as directed on the product label, allow the stated contact time, brush and flush.",cautions:"Do not mix with other cleaning products. Keep out of reach of children and follow the product label.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","No added chlorine","Cleans water marks and limescale deposits"]},
 "glass-mirror-cleaner":{name:"BIOstar Glass & Mirror Cleaner",purpose:"Glass and mirrors",description:"A cleaner for marks on glass and mirrors with a streak-free finish. The manufacturer packaging states 98% ingredients of natural origin and that the product contains natural aloe extract and natural vinegar essence.",usage:"Spray onto the surface and wipe with a clean cloth as directed on the product label.",cautions:"Test on a small, inconspicuous area before use and follow the product label.",features:["98% ingredients of natural origin according to the manufacturer","Contains natural aloe extract and natural vinegar essence","Streak-free finish on glass and mirrors"]},
 "universal-cleaner":{name:"BIOstar Universal Cleaner",purpose:"Washable surfaces, including floors",description:"A multi-purpose cleaner for a range of washable surfaces, including floors. The manufacturer packaging states 99% ingredients of natural origin and that the product contains natural lavender extract.",usage:"Dilute or apply as directed on the product label according to the surface and level of soil.",cautions:"Check surface compatibility and follow the product label before use.",features:["99% ingredients of natural origin according to the manufacturer","Contains natural lavender extract","For a range of washable surfaces, including floors"]},
 "laundry-capsules":{name:"BIOstar Laundry Capsules",purpose:"White and coloured laundry",description:"A 2-in-1 capsule detergent for white and coloured laundry. The manufacturer packaging states 100% natural plant extracts, natural lavender extract, and no added parabens or microplastics. The 100% statement applies to the plant extracts, not to the entire product.",usage:"With dry hands, place the recommended number of capsules in the drum before adding laundry. Follow the garment care instructions and product label.",cautions:"Do not pierce or handle capsules with wet hands. Keep out of reach of children and follow the product label.",features:["100% natural plant extracts (not a 100% natural-origin product claim)","Contains natural lavender extract","No added parabens or microplastics","2-in-1 capsules for white and coloured laundry"]},
 "eko-dishwasher-tablets":{name:"Ludwik EKO Dishwasher Tablets",purpose:"For dishwashers",description:"All-in-one dishwasher tablets with a baking soda system and biodegradable formula, with cleaning performance from 50°C according to the manufacturer packaging.",usage:"Use one tablet per wash without removing the water-soluble film. Follow the dishwasher manual and product packaging.",cautions:"Do not use on silver, aluminium, crystal, copper or wooden items. Follow the product packaging.",features:["Baking soda system","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C","85% of the packaging is made from recycled material"]},
 "eko-dishwasher-powder":{name:"Ludwik EKO Dishwasher Powder",purpose:"For dishwashers",description:"Dishwasher powder that can be adjusted to the level of soil and water hardness. It uses a baking soda system and biodegradable formula according to the manufacturer packaging.",usage:"Measure according to the level of soil and water hardness, following the product packaging and dishwasher manual.",cautions:"Do not use on silver, aluminium, crystal, copper or wooden items. Follow the product packaging.",features:["Baking soda system","Biodegradable formula","EU Ecolabel-marked product","Cleaning performance from 50°C","95% of the paper box is made from recycled material"]}
};
const approved=master.products.filter(p=>p.approvalStatus==="approved");
const englishVolume=value=>value.replace(/개입/g," count");
const englishCategory=value=>value==="식기세척기용 세제"?"Dishwasher detergent":value;
const familySlug=p=>p.brandSlug==="ludwik"?p.slug.replace(/-\d+(?:-\d+)?(?:pcs|kg)$/,''):p.slug;
const groups=[...new Map(approved.map(p=>[`${p.brandSlug}/${familySlug(p)}`,approved.filter(x=>`${x.brandSlug}/${familySlug(x)}`===`${p.brandSlug}/${familySlug(p)}`)])).entries()];
const brandPage=(brand)=>{const products=groups.filter(([key])=>key.startsWith(`${brand.toLowerCase()}/`));return `${hero(brand,brand==="BIOstar"?"Purpose-built care for everyday spaces":"Homecare experience that began in the kitchen","Explore verified product information for the products introduced in Korea by OLM International.")}<section class="section"><div class="container"><span class="eyebrow">AVAILABLE IN KOREA</span><h2 class="title">${brand} products</h2><div class="product-index-grid">${products.map(([key,items])=>{const slug=key.split('/')[1],en=productEnglish[slug],p=items[0];return `<article class="product-index-card"><img src="${p.images[0].src}" width="${p.images[0].width}" height="${p.images[0].height}" alt="${esc(en.name)}" loading="lazy"><div><span class="eyebrow">${brand}</span><h3>${esc(en.name)}</h3><p>${esc(items.map(x=>englishVolume(x.volume)).join(' · '))}</p><p>${esc(en.description)}</p><a class="btn" href="/en/brands/${key}/">Product details</a></div></article>`}).join('')}</div></div></section>`};
pages.biostar={title:"BIOstar Homecare Products | OLM International",description:"Explore verified information for nine BIOstar homecare products for kitchens, bathrooms, laundry and other spaces.",body:brandPage("BIOstar")};
pages.ludwik={title:"Ludwik | Polish Homecare Brand Since 1964",description:"Discover Ludwik and its EKO dishwasher tablets and powder available in Korea.",body:brandPage("Ludwik")};
const organization={"@type":"Organization","@id":`${site}/#organization`,name:"OLM International Corp.",url:`${site}/`,email:"khs@olm.kr"};
for(const [id,page] of Object.entries(pages)){
 const path=id==="home"?"/en/":id==="biostar"||id==="ludwik"?`/en/brands/${id}/`:`/en/${id}/`;
 const folder=id==="home"?new URL("en/",root):new URL(path.slice(1),root); await mkdir(folder,{recursive:true});
 const jsonLd={"@context":"https://schema.org","@graph":[organization,{"@type":"WebPage",url:`${site}${path}`,name:page.title,description:page.description,inLanguage:"en"}]};
 await writeFile(new URL("index.html",folder),layout({path,id,title:page.title,description:page.description,body:page.body,jsonLd}));
}
for(const [key,items] of groups){
 const slug=key.split('/')[1],en=productEnglish[slug],p=items[0],path=`/en/brands/${key}/`,volumes=items.map(x=>englishVolume(x.volume)).join(" · ");
 const facts=[["Brand",p.brand],["Category",englishCategory(p.category)],["Purpose",en.purpose],["Size / quantity",volumes],["Directions",en.usage],["Cautions",en.cautions],["Manufacturer",p.manufacturer||"Not stated in the reviewed source"],["Country of origin",p.countryOfOrigin==="폴란드"?"Poland":p.countryOfOrigin],["Korean distributor",p.distributor?"OLM International Corp.":"Not stated in the reviewed source"],["Last reviewed",p.lastReviewedAt]];
 const body=`<article class="product-page"><section class="product-hero"><div class="container product-hero-grid"><figure><img src="${p.images[0].src}" width="${p.images[0].width}" height="${p.images[0].height}" alt="${esc(en.name)}"></figure><div><nav class="breadcrumb"><a href="/en/">Home</a> / <a href="/en/brands/">Brands</a> / <a href="/en/brands/${p.brandSlug}/">${p.brand}</a></nav><span class="eyebrow">${p.brand} · PRODUCT INFORMATION</span><h1>${esc(en.name)}</h1><p class="product-volume">${esc(volumes)}</p><p class="lead">${esc(en.description)}</p><div class="product-actions"><a class="btn btn-primary" href="/en/brands/${p.brandSlug}/">${p.brand} brand page</a></div></div></div></section><section class="product-facts"><div class="container"><span class="eyebrow">VERIFIED PRODUCT FACTS</span><h2 class="title">Verified product information</h2><dl class="product-facts-grid">${facts.map(([a,b])=>`<div class="product-fact"><dt>${a}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl><h2 class="title">Verified features</h2><ul>${en.features.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="product-source-note">Information is based on the reviewed manufacturer materials. Always check the latest label on the product purchased before use.</p></div></section></article>`;
 const canonical=`${site}${path}`;
 const jsonLd={"@context":"https://schema.org","@graph":[organization,{"@type":"WebPage",url:canonical,name:en.name,description:en.description,inLanguage:"en"},{"@type":"Product",name:en.name,description:en.description,image:items.map(x=>`${site}${x.images[0].src}`),brand:{"@type":"Brand",name:p.brand},manufacturer:p.manufacturer?{"@type":"Organization",name:p.manufacturer}:undefined,category:englishCategory(p.category),url:canonical}]};
 const folder=new URL(path.slice(1),root);await mkdir(folder,{recursive:true});await writeFile(new URL("index.html",folder),layout({path,id:"brands",title:`${en.name} | OLM International`,description:en.description,body,jsonLd}));
}
export const englishRoutes=["/en/",...Object.keys(pages).filter(x=>x!=="home").map(id=>id==="biostar"||id==="ludwik"?`/en/brands/${id}/`:`/en/${id}/`),...groups.map(([key])=>`/en/brands/${key}/`)];
