import { mkdir, readFile, writeFile } from "node:fs/promises";
const root = new URL("../", import.meta.url);
const media = JSON.parse(await readFile(new URL("assets/data/media-data.json", root), "utf8"));
const image = key => media.images[key];
const imageTag = (key, decorative = false) => {
  const item = image(key);
  return `<img src="${item.src}" width="${item.width}" height="${item.height}" alt="${decorative ? "" : item.alt}">`;
};
const nav = [["회사소개","about"],["브랜드","brands"],["사업영역","business"],["파트너십","partnership"],["문의","contact"]];
const meta = {
  home:["오름인터내셔널 | 유럽 프리미엄 생활용품 브랜드 공식 파트너","Ludwik와 BIOstar의 대한민국 공식 파트너, 오름인터내셔널을 소개합니다."],
  about:["회사소개 | 오름인터내셔널","브랜드와 시장을 이해하고 오래가는 성장을 설계하는 오름인터내셔널입니다."],
  brands:["브랜드 | 오름인터내셔널","오름인터내셔널의 공식 파트너 브랜드 Ludwik와 BIOstar를 만나보세요."],
  ludwik:["Ludwik | 1964년부터 이어온 폴란드 홈케어","폴란드의 주방에서 시작해 생활 전반으로 확장된 Ludwik를 소개합니다."],
  biostar:["BIOstar | 자연에서 찾은 성분과 클리닝 기술","천연 유래 성분과 알로에, 라벤더 추출물, 유산균을 활용한 BIOstar를 소개합니다."],
  business:["사업영역 | 오름인터내셔널","해외 브랜드 소싱부터 국내 유통과 브랜드 빌딩까지 연결합니다."],
  partnership:["한국 시장 파트너십 | 오름인터내셔널","해외 생활용품 브랜드의 성공적인 한국 시장 진출을 함께 설계합니다."],
  contact:["문의 | 오름인터내셔널","소비자, 유통·입점, 해외 브랜드 파트너십 문의를 안내합니다."]
};
const pathOf = id => id === "home" ? "/" : id === "ludwik" || id === "biostar" ? `/brands/${id}/` : `/${id}/`;
const header = current => `<a class="skip-link" href="#main">본문 바로가기</a><header class="header"><div class="container header-inner"><a class="logo" href="/" aria-label="오름인터내셔널 홈"><span class="logo-mark" aria-hidden="true"></span><span>OLM</span></a><button class="menu-button" id="menu-open" aria-controls="primary-nav" aria-expanded="false"><span></span><span></span><span></span><span class="sr-only">메뉴 열기</span></button><nav class="nav" id="primary-nav" aria-label="주요 메뉴"><button class="menu-close" id="menu-close" aria-label="메뉴 닫기">✕</button>${nav.map(([n,id])=>`<a href="/${id}/"${current===id?' aria-current="page"':''}>${n}</a>`).join("")}</nav></div></header>`;
const footer = `<footer class="footer"><div class="container"><div class="footer-top"><a class="logo" href="/"><span class="logo-mark" aria-hidden="true"></span><span>OLM</span></a><div class="footer-info"><span><b>회사명</b> 오름인터내셔널</span><span><b>이메일</b> contact@example.com</span><span><b>대표 연락처</b> 준비 중</span><span><b>주소</b> 회사 주소 준비 중</span></div></div><div class="footer-bottom">© 2026 OLM. All rights reserved. &nbsp; <a href="/contact/">문의 안내</a></div></div></footer>`;
const layout = (id, body, schema="") => { const [title,desc]=meta[id]; const path=pathOf(id); return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="https://example.com${path}"><meta property="og:type" content="website"><meta property="og:locale" content="ko_KR"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:image" content="https://example.com${image("commonOg").src}"><meta property="og:url" content="https://example.com${path}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${image("favicon").src}" type="image/svg+xml"><link rel="stylesheet" href="/assets/css/style.css"><script type="application/ld+json">${schema||JSON.stringify({"@context":"https://schema.org","@type":"Organization","name":"오름인터내셔널","url":"https://example.com","email":"contact@example.com"})}</script></head><body>${header(id)}<main id="main">${body}</main>${footer}<script src="/assets/data/site-data.js"></script><script src="/assets/js/main.js"></script></body></html>`};
const pageHero=(eyebrow,title,lead)=>`<section class="page-hero"><div class="container"><div class="breadcrumb"><a href="/">홈</a> / ${eyebrow}</div><span class="eyebrow">${eyebrow}</span><h1 class="display">${title}</h1><p class="lead">${lead}</p></div></section>`;
const home = `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><span class="eyebrow">Official partner in Korea</span><h1 class="display">유럽 프리미엄 생활용품 브랜드의<br>한국 공식 파트너</h1><p>오름인터내셔널이 Ludwik와 BIOstar를 대한민국에 공식적으로 소개합니다.</p><div class="btn-row"><a class="btn btn-primary" href="/brands/">브랜드 살펴보기</a><a class="btn btn-light" href="#retailers">공식 판매처 보기</a></div></div><div class="hero-art" aria-hidden="true">${imageTag("ludwikHero", true)}${imageTag("biostarHero", true)}</div></div></section>
<div class="trust-strip"><div class="container trust-inner"><strong>브랜드의 가치가 한국의 일상에 닿도록</strong><span>Official partnership · Local market expertise · Sustainable growth</span></div></div>
<section class="section ludwik"><div class="container split"><div><span class="eyebrow">Ludwik</span><div class="stat">1964</div><h2 class="title">생활의 깨끗함을 이어온 폴란드 홈케어</h2><p class="lead">1964년부터 이어온 폴란드의 생활 세정 브랜드, Ludwik. 주방에서 세탁과 홈케어까지, 오랜 경험을 바탕으로 일상의 깨끗함을 만들어갑니다.</p><div class="keyword-list"><span>Poland</span><span>Kitchen</span><span>Laundry</span></div><a class="link-arrow" href="/brands/ludwik/">Ludwik 자세히 보기 →</a></div><div class="visual">${imageTag("ludwikHero")}<span class="visual-label">Since 1964 · Poland</span></div></div></section>
<section class="section biostar"><div class="container split"><div class="visual">${imageTag("biostarHero")}<span class="visual-label">Nature × Cleaning technology</span></div><div><span class="eyebrow">BIOstar</span><h2 class="title">자연에서 찾은 성분에<br>클리닝 기술을 더하다</h2><p class="lead">천연 유래 성분과 식물 추출물에서 시작한 BIOstar. 알로에와 유산균을 활용한 새로운 클리닝 아이디어로 집 안의 다양한 공간을 깨끗하게 관리합니다.</p><div class="keyword-list"><span>천연 알로에 추출물</span><span>천연 라벤더 추출물</span><span>유산균</span></div><a class="link-arrow" href="/brands/biostar/">BIOstar 자세히 보기 →</a></div></div></section>
<section class="section"><div class="container"><span class="eyebrow">What we do</span><h2 class="title">좋은 브랜드를 발견하고<br>한국 시장의 성장을 설계합니다</h2><div class="cap-grid"><article class="cap-item"><span class="num">01</span><h3>브랜드 소싱</h3><p>시장과 고객의 생활을 이해해 성장 가능성이 있는 해외 브랜드를 발굴합니다.</p></article><article class="cap-item"><span class="num">02</span><h3>브랜드 빌딩</h3><p>브랜드 본연의 가치를 존중하며 한국 소비자에게 맞는 언어로 전달합니다.</p></article><article class="cap-item"><span class="num">03</span><h3>채널 운영</h3><p>온라인 유통 경험을 토대로 브랜드와 고객이 만나는 접점을 운영합니다.</p></article></div></div></section>
<section class="section-sm" id="retailers"><div class="container"><span class="eyebrow">Official retailers</span><h2 class="title">공식 판매채널</h2><p class="lead">신뢰할 수 있는 공식 판매처를 준비하고 있습니다. 판매처가 확정되는 대로 이곳에서 안내합니다.</p><div class="notice">공식 판매처 링크 업데이트 예정</div></div></section>
<section class="section dark"><div class="container b2b"><div><span class="eyebrow">Partnership</span><h2 class="title">한국 시장의 다음 성장을<br>함께 만들 브랜드를 기다립니다</h2><p class="lead">브랜드 발굴부터 현지화, 유통 운영과 장기적인 브랜드 빌딩까지 함께합니다.</p></div><a class="btn btn-light" href="/partnership/">파트너십 알아보기</a></div></section>`;
const brands = `${pageHero("Brands","서로 다른 개성,<br>하나의 신뢰","오름인터내셔널은 각 브랜드의 고유한 역사와 철학을 존중하며 한국의 일상에 연결합니다.")}<section class="section ludwik"><div class="container split"><div><span class="eyebrow">01 · Ludwik</span><h2 class="title">1964년 폴란드의 주방에서 시작된 생활 세정 브랜드</h2><p>오랜 헤리티지와 폭넓은 홈케어 제품군으로 생활 곳곳의 깨끗함을 제안합니다.</p><a class="link-arrow" href="/brands/ludwik/">브랜드 스토리 →</a></div><div class="visual">${imageTag("ludwikHero")}</div></div></section><section class="section biostar"><div class="container split"><div class="visual">${imageTag("biostarHero")}</div><div><span class="eyebrow">02 · BIOstar</span><h2 class="title">자연에서 찾은 성분과 클리닝 기술의 만남</h2><p>천연 유래 성분과 식물 추출물, 유산균을 활용한 새로운 홈케어 아이디어를 전합니다.</p><a class="link-arrow" href="/brands/biostar/">브랜드 스토리 →</a></div></div></section>`;
const ludwik = `<section class="brand-hero ludwik"><div class="container brand-hero-grid"><div><div class="breadcrumb"><a href="/">홈</a> / <a href="/brands/">브랜드</a> / Ludwik</div><span class="eyebrow">Since 1964 · Poland</span><h1 class="display">폴란드의 주방에서 시작해 생활 전반으로 확장된 클리닝 브랜드</h1><p class="lead">주방세제로 시작한 경험을 세탁과 홈케어까지 이어갑니다.</p></div>${imageTag("ludwikHero")}</div></section><section class="section"><div class="container split"><div><div class="stat">1964</div><h2 class="title">첫 시작부터 이어진<br>생활 세정의 경험</h2></div><div><p class="lead">Ludwik는 1964년 폴란드 최초의 주방세제로 출발했습니다. 주방에서 쌓은 오랜 경험을 바탕으로 오늘날 세탁과 생활 공간 전반을 아우르는 홈케어 제품군으로 확장되었습니다.</p></div></div></section><section class="section ludwik"><div class="container"><span class="eyebrow">Homecare range</span><h2 class="title">국내 취급 제품 영역</h2><div class="feature-row"><article><h3>주방 세정</h3><p>식기와 주방 공간을 위한 세정 제품군</p></article><article><h3>세탁 케어</h3><p>매일의 옷과 섬유를 관리하는 제품군</p></article><article><h3>홈케어</h3><p>집 안의 다양한 표면과 공간을 위한 제품군</p></article></div><p class="notice">국내 공식 취급 제품 목록과 이미지는 자료 확정 후 업데이트됩니다.</p></div></section><section class="section dark"><div class="container b2b"><div><h2 class="title">Ludwik를 만나는 공식 채널</h2><p class="lead">확인된 국내 공식 판매처만 안내합니다.</p></div><a class="btn btn-light" href="/#retailers">공식 판매처 보기</a></div></section>`;
const biostar = `<section class="brand-hero biostar"><div class="container brand-hero-grid"><div><div class="breadcrumb"><a href="/">홈</a> / <a href="/brands/">브랜드</a> / BIOstar</div><span class="eyebrow">Nature meets technology</span><h1 class="display">자연에서 찾은 성분에 클리닝 기술을 더하다</h1><p class="lead">집 안의 다양한 공간을 위한 새로운 홈케어 아이디어를 제안합니다.</p></div>${imageTag("biostarHero")}</div></section><section class="section"><div class="container"><span class="eyebrow">Thoughtful ingredients</span><h2 class="title">자연에서 시작한<br>클리닝 포뮬러</h2><div class="feature-row"><article><h3>천연 유래 성분</h3><p>자연에서 찾은 성분을 클리닝 기술과 조화롭게 구성합니다.</p></article><article><h3>천연 알로에 추출물</h3><p>알로에에서 영감을 받은 브랜드의 성분 접근을 소개합니다.</p></article><article><h3>천연 라벤더 추출물</h3><p>일상의 세정 경험에 식물 추출물의 아이디어를 더합니다.</p></article></div></div></section><section class="section biostar"><div class="container split"><div class="visual">${imageTag("biostarIngredients")}</div><div><span class="eyebrow">Cleaning idea</span><h2 class="title">유산균을 활용한<br>BIOstar만의 클리닝 아이디어</h2><p class="lead">자연 유래 성분과 브랜드의 세정 기술을 결합해 새로운 홈케어 방식을 제안합니다.</p></div></div></section><section class="section"><div class="container"><span class="eyebrow">By space</span><h2 class="title">생활 공간에 맞춘 제품군</h2><div class="cap-grid"><article class="cap-item"><span class="num">Kitchen</span><h3>주방</h3><p>매일 사용하는 주방 공간을 위한 제품군</p></article><article class="cap-item"><span class="num">Bathroom</span><h3>욕실</h3><p>습기와 물 사용이 잦은 욕실을 위한 제품군</p></article><article class="cap-item"><span class="num">Laundry</span><h3>세탁 홈케어</h3><p>의류와 세탁 공간을 관리하는 제품군</p></article></div><div class="notice"><b>제품별 인증</b><br>인증은 확인된 개별 제품에만 연결해 표시합니다. 공식 자료 업데이트 예정입니다.</div></div></section><section class="section dark"><div class="container b2b"><div><h2 class="title">BIOstar를 만나는 공식 채널</h2><p class="lead">확인된 국내 공식 판매처만 안내합니다.</p></div><a class="btn btn-light" href="/#retailers">공식 판매처 보기</a></div></section>`;
const about = `${pageHero("About","좋은 브랜드가<br>더 높이 오를 수 있도록","오름인터내셔널은 브랜드의 본질과 한국 소비자의 일상을 연결하는 공식 파트너입니다.")}<section class="section"><div class="container split"><div><span class="eyebrow">Our philosophy</span><h2 class="title">빠른 유통보다<br>오래가는 브랜드를 만듭니다</h2></div><div><p class="lead">제품을 소개하는 데서 그치지 않고, 브랜드가 지켜온 가치와 한국 시장의 맥락을 함께 이해합니다. 분명한 포지셔닝과 책임 있는 채널 운영으로 지속 가능한 성장을 지향합니다.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">Milestones</span><h2 class="title">함께 쌓아갈 이정표</h2><div class="timeline"><article><time>NOW</time><h3>공식 파트너 브랜드 집중</h3><p>Ludwik와 BIOstar의 가치와 제품을 한국 소비자에게 일관되게 소개합니다.</p></article><article><time>NEXT</time><h3>생활용품 브랜드 성장 기반 강화</h3><p>브랜드와 고객을 잇는 콘텐츠, 마케팅, 유통 접점을 정교하게 확장합니다.</p></article></div></div></section><section class="section"><div class="container"><span class="eyebrow">Official partnership</span><h2 class="title">파트너십·인증</h2><p class="lead">공식 파트너십 증빙과 제품별 인증 자료는 확인된 공식 자료를 기준으로 이 영역에 게시합니다.</p><div class="notice">공식 증빙 자료 업데이트 예정 · 제품 인증은 해당 제품 단위로 표시</div></div></section>`;
const business = `${pageHero("Business","발굴에서 안착까지,<br>하나의 흐름으로","해외 브랜드가 한국 시장에서 자신의 가치를 선명하게 전하고 성장하도록 전 과정을 연결합니다.")}<section class="section"><div class="container"><span class="eyebrow">Capabilities</span><h2 class="title">오름인터내셔널의 사업 역량</h2><div class="cap-grid"><article class="cap-item"><span class="num">01</span><h3>해외 브랜드 소싱</h3><p>시장 가능성과 브랜드 철학, 제품 경쟁력을 함께 살펴 좋은 파트너를 발굴합니다.</p></article><article class="cap-item"><span class="num">02</span><h3>국내 마케팅·브랜드 빌딩</h3><p>한국 고객에게 닿는 언어와 콘텐츠로 브랜드의 가치를 일관되게 전달합니다.</p></article><article class="cap-item"><span class="num">03</span><h3>온라인 유통채널 운영</h3><p>고객 접점과 구매 여정을 관리하며 신뢰할 수 있는 공식 판매 경험을 만듭니다.</p></article></div></div></section><section class="section dark"><div class="container"><span class="eyebrow">Go-to-market flow</span><h2 class="title">한국 시장 안착을 위한 흐름</h2><div class="steps"><article class="step"><span class="num">01 · Discover</span><h3>브랜드 발굴</h3><p>브랜드 목표와 시장 적합성을 검토합니다.</p></article><article class="step"><span class="num">02 · Build</span><h3>현지화와 론칭</h3><p>포지셔닝, 콘텐츠, 채널 전략을 설계합니다.</p></article><article class="step"><span class="num">03 · Grow</span><h3>운영과 성장</h3><p>시장 반응을 바탕으로 장기 성장을 함께 만듭니다.</p></article></div></div></section>`;
const partnership = `${pageHero("Partnership","Your trusted partner<br>for the Korean market","We help international homecare brands enter, connect, and grow in Korea with a long-term perspective.")}<section class="section"><div class="container split"><div><span class="eyebrow">Local expertise</span><h2 class="title">브랜드의 기준을 지키며<br>한국 시장과 연결합니다</h2></div><div><p class="lead">오름인터내셔널은 단순한 유통을 넘어 브랜드의 목소리와 한국 소비자의 기대 사이를 연결합니다. 시장 이해, 현지화, 채널 운영을 하나의 팀처럼 함께합니다.</p></div></div></section><section class="section-sm" style="background:var(--paper)"><div class="container"><span class="eyebrow">Our support</span><h2 class="title">지원 범위</h2><div class="feature-row"><article><h3>Market entry</h3><p>시장 맥락과 고객 접점을 고려한 진입 방향을 함께 설계합니다.</p></article><article><h3>Brand building</h3><p>브랜드 아이덴티티를 존중하는 현지 콘텐츠와 커뮤니케이션을 구축합니다.</p></article><article><h3>Channel operation</h3><p>공식 판매채널을 운영하고 지속적인 성장을 위한 기반을 관리합니다.</p></article></div></div></section><section class="section"><div class="container"><span class="eyebrow">How we collaborate</span><h2 class="title">협업 절차</h2><div class="timeline"><article><time>STEP 01</time><h3>Introduction</h3><p>브랜드와 제품, 한국 시장에서의 목표를 공유합니다.</p></article><article><time>STEP 02</time><h3>Market &amp; fit review</h3><p>제품군과 시장 적합성, 협업 범위를 함께 검토합니다.</p></article><article><time>STEP 03</time><h3>Launch plan</h3><p>현지화, 채널, 마케팅 실행 계획을 구체화합니다.</p></article><article><time>STEP 04</time><h3>Grow together</h3><p>론칭 이후 성과를 살피며 장기적인 성장을 만듭니다.</p></article></div></div></section><section class="section dark"><div class="container b2b"><div><h2 class="title">Let’s build your brand’s<br>next chapter in Korea.</h2><p class="lead">영문 제안 자료와 상세 협업 문의는 연락처를 통해 요청해 주세요.</p></div><a class="btn btn-light" href="/contact/?type=partnership">파트너십 문의</a></div></section>`;
const contact = `${pageHero("Contact","함께 이야기해 주세요","문의 목적을 선택해 남겨 주시면 담당 범위에 따라 안내할 수 있도록 준비하겠습니다.")}<section class="section"><div class="container contact-grid"><aside><span class="eyebrow">Contact information</span><h2 class="title">연락처 안내</h2><ul class="contact-list"><li><b>이메일</b><br><a href="mailto:contact@example.com">contact@example.com</a></li><li><b>대표 연락처</b><br>준비 중</li><li><b>주소</b><br>회사 주소 준비 중</li></ul><p class="notice">공식 연락처와 주소는 최종 확인 후 업데이트됩니다.</p></aside><div><form id="contact-form"><div class="form-grid"><div class="field"><label for="type">문의 유형</label><select id="type" name="type" required><option value="">선택해 주세요</option><option>소비자 문의</option><option>유통·입점 문의</option><option value="partnership">해외 브랜드 파트너십 문의</option></select></div><div class="field"><label for="name">이름 / 회사명</label><input id="name" name="name" autocomplete="name" required></div><div class="field"><label for="email">이메일</label><input id="email" name="email" type="email" autocomplete="email" required></div><div class="field"><label for="phone">연락처 <span class="sr-only">선택 사항</span></label><input id="phone" name="phone" autocomplete="tel"></div><div class="field full"><label for="message">문의 내용</label><textarea id="message" name="message" required></textarea></div><div class="field full"><label><input type="checkbox" required> 문의 응대를 위한 개인정보 수집에 동의합니다.</label></div></div><button class="btn btn-primary" type="submit">문의 내용 확인</button><p class="form-status" id="form-status" tabindex="-1" role="status">현재 온라인 전송 설정을 준비 중입니다. 제출하면 대체 연락 방법을 안내합니다.</p></form></div></div></section>`;
const breadcrumbSchema = id => JSON.stringify({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"홈","item":"https://example.com/"},{"@type":"ListItem","position":2,"name":"브랜드","item":"https://example.com/brands/"},{"@type":"ListItem","position":3,"name":id === "ludwik" ? "Ludwik":"BIOstar","item":`https://example.com/brands/${id}/`}]});
const pages={home,about,brands,ludwik,biostar,business,partnership,contact};
for (const [id,body] of Object.entries(pages)) {
  const folder = id === "home" ? root : id === "ludwik" || id === "biostar" ? new URL(`brands/${id}/`,root) : new URL(`${id}/`,root);
  await mkdir(folder,{recursive:true});
  await writeFile(new URL("index.html",folder),layout(id,body,["ludwik","biostar"].includes(id)?breadcrumbSchema(id):""));
}
